/*
 * CoreFreq
 * Copyright (C) 2015-2026 CYRIL COURTIAT
 * Licenses: GPL2
 */

#define RSC_THEME_USR1_CODE		/* 72 chars */			\
"        Strawberry theme by CyrIng.  Updated by CyrIng - June 2025      "

#define RSC_UI_THM_USR1_ATTR						\
{									\
	[UI_FUSE_RESET_LAYER] = {					\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_FUSE_PAINT_LAYER] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_MAKE_TITLE_UNFOCUS] = {					\
		.fg = BLACK, .un = 0, .bg = MAGENTA, .bf = 1		\
	},								\
	[UI_MAKE_TITLE_FOCUS] = {					\
		.fg = MAGENTA, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_MAKE_BORDER_UNFOCUS] = {					\
		.fg = BLACK, .un = 0, .bg = MAGENTA, .bf = 1		\
	},								\
	[UI_MAKE_BORDER_FOCUS] = {					\
		.fg = WHITE, .un = 0, .bg = MAGENTA, .bf = 1		\
	},								\
	[UI_MAKE_SELECT_UNFOCUS] = {					\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_MAKE_SELECT_FOCUS] = {					\
		.fg = BLACK, .un = 0, .bg = MAGENTA, .bf = 0		\
	},								\
	[UI_MAKE_PRINT_UNFOCUS] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_MAKE_PRINT_FOCUS] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_MAKE_PRINT_DROP] = {					\
		.fg = BLACK, .un = 0, .bg = MAGENTA, .bf = 0		\
	},								\
	[UI_LAYOUT_LCD_RESET] = {					\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_CLOCK_LOW] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_CLOCK_MEDIUM] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_LCD_CLOCK_HIGH] = {					\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_COUNTER_LOW] =  {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_COUNTER_MEDIUM] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_COUNTER_HIGH] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_LCD_LOAD_LOW] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_LOAD_MEDIUM] =  {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_LCD_LOAD_HIGH] = {					\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_IDLE_LOW] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_IDLE_MEDIUM] =  {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_LCD_IDLE_HIGH] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_SYSTEM_LOW] = {					\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_SYSTEM_MEDIUM] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_LCD_SYSTEM_HIGH] =  {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_UBENCH] = {						\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_HEADER_PROC_BRAND] = {				\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_HEADER_PROC_BRAND_FILL] = {				\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_HEADER_ARCHITECTURE] = {				\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_HEADER_ARCH_FILL] = {				\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_HEADER_BCLK_FILL] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_RULER_INSTRUCTIONS] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_CYCLES] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_CSTATES] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_INTERRUPTS] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_PACKAGE] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_TASKS_FILL] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_TASKS_TRACKING] = {				\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_ENERGY] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_SLICE] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_CUSTOM] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_ENABLE_0] =  {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_ENABLE_1] =  {				\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_ENABLE_2] =  {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_TSC_NONE] =  {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_TSC_VAR] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_TSC_INV] = {					\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_TM_0] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_TM_1] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_TM_2] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_TM_3] = {					\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_FILL] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_GATE] = {					\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_SPACE] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_LEFT_BRACE] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_RIGHT_BRACE] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_KERNEL_VERSION] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_UNMAP_GATE] = {				\
		.fg = RED, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_DMI_STRING] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_BCLK_TO_VIEW] = {					\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_ROW_CPU_OFFLINE] =  {				\
		.fg = WHITE, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_LOAD_TAB_DIM] = {				\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_LOAD_TAB_BRIGHT] = {				\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_ILLUMINATES_CPU_OFF] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_ILLUMINATES_CPU_ON] = {					\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_ILLUMINATES_CPU_SP] = {					\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_ILLUMINATES_CPU_SP_HYBRID] = {				\
		.fg = GREEN, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_DRAW_FREQUENCY_LOAD_CLEAR] = {				\
		.fg = WHITE, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_FREQUENCY_LOAD_LOW] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_DRAW_FREQUENCY_LOAD_MEDIUM] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_FREQUENCY_LOAD_HIGH] = {				\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_DRAW_ALTMONITOR_TASKS_CLEAR] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_ALTMONITOR_TASKS_SPACE] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_MONITOR_FREQUENCY_NOMINAL] =  {			\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_MONITOR_FREQUENCY_LOW] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_DRAW_MONITOR_FREQUENCY_HIGH] = {				\
		.fg = RED, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_MONITOR_FREQUENCY_HOT] = {				\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_CARD_CORE_OFFLINE] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_CARD_RAM_2DIGITS] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_CARD_RAM_3DIGITS] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_CARD_CORE_NOMINAL] =  {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_CARD_CORE_LOW] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_DRAW_CARD_CORE_MEDIUM] = {					\
		.fg = RED, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_CARD_CORE_HIGH] = {					\
		.fg = RED, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_DRAW_CARD_TASK_FILL] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_WIN_MENU_UNSELECT] = {					\
		.fg = BLACK, .un = 0, .bg = MAGENTA, .bf = 1		\
	},								\
	[UI_WIN_MENU_SELECT] = {					\
		.fg = MAGENTA, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_MENU_TITLE_UNFOCUS] =  {				\
		.fg = BLACK, .un = 0, .bg = MAGENTA, .bf = 0		\
	},								\
	[UI_WIN_MENU_TITLE_FOCUS] = {					\
		.fg = BLACK, .un = 0, .bg = MAGENTA, .bf = 1		\
	},								\
	[UI_WIN_MENU_ERASE_CELL] = {					\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_SORT_BY_FIELD_TITLE] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_WIN_TRACKING_PARENT_PROCESS] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_TRACKING_CHILD_PROCESS] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_TRACKING_THIS_PARENT] = {				\
		.fg = MAGENTA, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_TRACKING_THIS_CHILD] = {				\
		.fg = MAGENTA, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_TRACKING_COUNTERS] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_TRACKING_TITLE] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_WIN_HOT_PLUG_CPU_TITLE] =  {				\
		.fg = WHITE, .un = 0, .bg = MAGENTA, .bf = 1		\
	},								\
	[UI_WIN_SELECT_IDLE_RESET] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_SELECT_IDLE_POLL] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_SELECT_IDLE_CURRENT] = {				\
		.fg = MAGENTA, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_POPUP_MSG_ITEM] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_POPUP_MSG_SELECT_UNFOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_POPUP_MSG_SELECT_FOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_POPUP_MSG_BORDER_UNFOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = RED, .bf = 0		\
	},								\
	[UI_WIN_POPUP_MSG_BORDER_FOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = RED, .bf = 1		\
	},								\
	[UI_WIN_POPUP_MSG_TITLE_UNFOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = RED, .bf = 0		\
	},								\
	[UI_WIN_POPUP_MSG_TITLE_FOCUS] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_WIN_EXIT_ISSUE_RECORDER] = {				\
		.fg = MAGENTA, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_ISSUE_STRESS] = {					\
		.fg = MAGENTA, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_ISSUE_OS_CPU_IDLE] = {				\
		.fg = MAGENTA, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_HEADER] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_EXIT_BLANK] =  {					\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_CONFIRM] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_FOOTER] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_BOX_DISABLE_STATE] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_BOX_ENABLE_STATE] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_BOX_BLANK] = {						\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_BOX_DESC] = {						\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_BOX_INTERVAL] = {						\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_BOX_EXPERIMENTAL_NOMINAL] = {				\
		.fg = MAGENTA, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_BOX_EXPERIMENTAL_WARNING] = {				\
		.fg = RED, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_DROP_IDLE_ROUTE] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_BOX_TOOLS_STOP] =  {					\
		.fg = RED, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WHEEL_CURRENT] = {						\
		.fg = MAGENTA, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WHEEL_SELECT] = {						\
		.fg = BLACK, .un = 0, .bg = MAGENTA, .bf = 0		\
	},								\
	[UI_WHEEL_LIST] = {						\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	}								\
}

#define RSC_VOID_THM_USR1_ATTR						\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_RUN_STATE_COLOR_THM_USR1_ATTR	\
{						\
	HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,	\
	HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,	\
	HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,	\
	HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,	\
	HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW 	\
}

#define RSC_UNINT_STATE_COLOR_THM_USR1_ATTR	\
{						\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,	\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,	\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,	\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,	\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW 	\
}

#define RSC_ZOMBIE_STATE_COLOR_THM_USR1_ATTR	\
{						\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW,	\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW,	\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW,	\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW,	\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW 	\
}

#define RSC_SLEEP_STATE_COLOR_THM_USR1_ATTR	\
{						\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,	\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,	\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,	\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,	\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW 	\
}

#define RSC_WAIT_STATE_COLOR_THM_USR1_ATTR	\
{						\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,	\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,	\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,	\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,	\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW 	\
}

#define RSC_OTHER_STATE_COLOR_THM_USR1_ATTR	\
{						\
	LGW,LGW,LGW,LGW,LGW,LGW,LGW,LGW,	\
	LGW,LGW,LGW,LGW,LGW,LGW,LGW,LGW,	\
	LGW,LGW,LGW,LGW,LGW,LGW,LGW,LGW,	\
	LGW,LGW,LGW,LGW,LGW,LGW,LGW,LGW,	\
	LGW,LGW,LGW,LGW,LGW,LGW,LGW,LGW 	\
}

#define RSC_TRACKER_STATE_COLOR_THM_USR1_ATTR	\
{						\
	LKM,LKM,LKM,LKM,LKM,LKM,LKM,LKM,	\
	LKM,LKM,LKM,LKM,LKM,LKM,LKM,LKM,	\
	LKM,LKM,LKM,LKM,LKM,LKM,LKM,LKM,	\
	LKM,LKM,LKM,LKM,LKM,LKM,LKM,LKM,	\
	LKM,LKM,LKM,LKM,LKM,LKM,LKM,LKM 	\
}

#define RSC_LAYOUT_HEADER_PROC_THM_USR1_ATTR				\
{									\
	HRW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW 		\
}

#define RSC_LAYOUT_HEADER_CPU_THM_USR1_ATTR				\
{									\
	HKW,LMW,LMW,LMW,LMW,HKW,LMW,LMW,LMW,LMW,HKW,HKW,HKW		\
}

#define RSC_LAYOUT_HEADER_ARCH_THM_USR1_ATTR				\
{									\
	HCW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW	\
}

#define RSC_LAYOUT_HEADER_CACHE_L1_THM_USR1_ATTR			\
{									\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,				\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,LMW,LMW,LMW,			\
	HKW,HKW,HKW,HKW,HKW,LMW,LMW,LMW,HKW,HKW 			\
}

#define RSC_LAYOUT_HEADER_BCLK_THM_USR1_ATTR				\
{									\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,		\
	HMW,HMW,LMW,LMW,LMW,HKW,LMW,LMW,LMW,HKW,LMW,LMW,LMW,HKW,HKW,HKW \
}

#define RSC_LAYOUT_HEADER_CACHES_THM_USR1_ATTR				\
{									\
	HKW,HKW,HKW,LMW,LMW,LMW,LMW,LMW,HKW,HKW,			\
	HKW,HKW,HKW,LMW,LMW,LMW,LMW,LMW,LMW,HKW,HKW			\
}

#define RSC_LAYOUT_RULER_LOAD_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,_HCW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_VAR_LOAD_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW 							\
}

#define RSC_LAYOUT_RULER_REL_LOAD_THM_USR1_ATTR \
	RSC_LAYOUT_RULER_VAR_LOAD_THM_USR1_ATTR

#define RSC_LAYOUT_RULER_ABS_LOAD_THM_USR1_ATTR \
	RSC_LAYOUT_RULER_VAR_LOAD_THM_USR1_ATTR

#define RSC_LAYOUT_MONITOR_FREQUENCY_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	HKW,HKW,HKW,HKW,HKW,HKW,LKW,LKW,LKW,HKW,HKW,HKW,HKW		\
}

#define RSC_LAYOUT_MONITOR_INST_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW		\
}

#define RSC_LAYOUT_MONITOR_COMMON_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW		\
}

#define RSC_LAYOUT_MONITOR_TASKS_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_MONITOR_SLICE_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HRW,HRW,HRW,\
	HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW	\
}

#define RSC_LAYOUT_CUSTOM_FIELD_THM_USR1_ATTR				\
{									\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,				\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,				\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,			\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,				\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,				\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,				\
	HKW,HKW,HKW,HKW,						\
	LKW,LKW,LKW,HKW,						\
	HKW,HKW,HKW,HKW,						\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,				\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,				\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,				\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,				\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,				\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,				\
	LKW,LKW,LKW,LKW,LKW,LKW,HKW,					\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,					\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,					\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,					\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,					\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW 	\
}

#define RSC_LAYOUT_RULER_FREQUENCY_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_FREQUENCY_AVG_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,HKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_FREQUENCY_PKG_THM_USR1_ATTR			\
{									\
	_HCW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_INST_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_CYCLES_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_CSTATES_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_INTERRUPTS_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_PACKAGE_THM_USR1_ATTR	RSC_VOID_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW \
}

#define RSC_LAYOUT_PACKAGE_PC02_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC03_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC04_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC06_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC07_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC08_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC09_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC10_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_MC06_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_CTR0_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_CTR1_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_CTR2_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_CTR3_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_CTR4_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_CTR5_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_CTR6_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_CTR7_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_UNCORE_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_PACKAGE_FABRIC_THM_USR1_ATTR \
	RSC_LAYOUT_PACKAGE_UNCORE_THM_USR1_ATTR

#define RSC_LAYOUT_RULER_TASKS_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_TASKS_STATE_SORTED_THM_USR1_ATTR			\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,			\
	LKW,LMW,LMW,LMW,LMW,LMW,HKW,LKW, LKW,LKW,LKW			\
}

#define RSC_LAYOUT_TASKS_RUNTIME_SORTED_THM_USR1_ATTR			\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,			\
	LKW,LMW,LMW,LMW,LMW,LMW,LMW,LMW, HKW,LKW,LKW			\
}

#define RSC_LAYOUT_TASKS_USRTIME_SORTED_THM_USR1_ATTR			\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,			\
	LKW,LMW,LMW,LMW,LMW,LMW,LMW,LMW, LMW,HKW,LKW			\
}

#define RSC_LAYOUT_TASKS_SYSTIME_SORTED_THM_USR1_ATTR			\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,			\
	LKW,LMW,LMW,LMW,LMW,LMW,LMW,LMW, HKW,LKW,LKW			\
}

#define RSC_LAYOUT_TASKS_PROCESS_SORTED_THM_USR1_ATTR			\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,			\
	LKW,LMW,LMW,LMW,HKW,LKW,LKW,LKW, LKW,LKW,LKW			\
}

#define RSC_LAYOUT_TASKS_COMMAND_SORTED_THM_USR1_ATTR			\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,			\
	LKW,LMW,LMW,LMW,LMW,LMW,LMW,LMW, HKW,LKW,LKW			\
}

#define RSC_LAYOUT_TASKS_REVERSE_SORT_OFF_THM_USR1_ATTR 		\
{									\
	LKW,LKW,LKW,LKW,LKW,_HCW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW	\
}

#define RSC_LAYOUT_TASKS_REVERSE_SORT_ON_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,_HCW,LKW,LKW,LKW,HKW,LMW,LMW,LMW,HKW,LKW	\
}

#define RSC_LAYOUT_TASKS_VALUE_SWITCH_THM_USR1_ATTR			\
{									\
	LKW,_HCW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW		\
}

#define RSC_LAYOUT_TASKS_VALUE_OFF_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW							\
}

#define RSC_LAYOUT_TASKS_VALUE_ON_THM_USR1_ATTR 			\
{									\
	LMW,LMW,LMW							\
}

#define RSC_LAYOUT_TASKS_TRACKING_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW					\
}

#define RSC_LAYOUT_RULER_SENSORS_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_PWR_DOMAIN_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,\
	LKW,LKW,HKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_PWR_UNCORE_THM_USR1_ATTR	\
	RSC_LAYOUT_RULER_PWR_DOMAIN_THM_USR1_ATTR

#define RSC_LAYOUT_RULER_PWR_PLATFORM_THM_USR1_ATTR	\
	RSC_LAYOUT_RULER_PWR_DOMAIN_THM_USR1_ATTR

#define RSC_LAYOUT_RULER_PWR_SOC_THM_USR1_ATTR		\
	RSC_LAYOUT_RULER_PWR_DOMAIN_THM_USR1_ATTR

#define RSC_LAYOUT_RULER_VOLTAGE_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_VPKG_SOC_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,HKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_VPKG_SAV_THM_USR1_ATTR 			\
	RSC_LAYOUT_RULER_VPKG_SOC_THM_USR1_ATTR

#define RSC_LAYOUT_RULER_ENERGY_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_POWER_THM_USR1_ATTR	\
	RSC_LAYOUT_RULER_ENERGY_THM_USR1_ATTR

#define RSC_LAYOUT_RULER_SLICE_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_CUSTOM_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_FOOTER_TECH_ARM_THM_USR1_ATTR			\
{									\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,	\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,	\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW \
}

#define RSC_LAYOUT_FOOTER_VOLT_TEMP_THM_USR1_ATTR			\
{									\
	LKW,HKW,LKW,LKW,LKW,LKW,HKW,HKW,LKW,HKW,HKW,HKW,HKW,LKW,HKW	\
}

#define RSC_LAYOUT_FOOTER_SYSTEM_THM_USR1_ATTR				\
{									\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,	\
	HKW,HKW,HKW,HKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,	\
	LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW 	\
}

#define RSC_LAYOUT_CARD_CORE_ONLINE_THM_USR1_ATTR			\
{									\
	HKW,HKW,LMW,LMW,LMW,HKW,HKW,HKW,HKW,HKW,HKW,HKW 		\
}

#define RSC_LAYOUT_CARD_CORE_ONLINE_COND0_THM_USR1_ATTR \
	RSC_LAYOUT_CARD_CORE_ONLINE_THM_USR1_ATTR

#define RSC_LAYOUT_CARD_CORE_ONLINE_COND1_THM_USR1_ATTR \
	RSC_LAYOUT_CARD_CORE_ONLINE_THM_USR1_ATTR

#define RSC_LAYOUT_CARD_CORE_OFFLINE_THM_USR1_ATTR			\
{									\
	HKW,HKW,LKW,LKW,LKW,HKW,HKW,LKW,LKW,LKW,HKW,HKW 		\
}

#define RSC_LAYOUT_CARD_CLK_THM_USR1_ATTR				\
{									\
	HKW,HKW,LMW,LMW,LMW,HKW,LMW,HKW,HKW,HKW,HKW,HKW 		\
}

#define RSC_LAYOUT_CARD_UNCORE_THM_USR1_ATTR				\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,LMW,LMW,HKW 		\
}

#define RSC_LAYOUT_CARD_BUS_THM_USR1_ATTR				\
{									\
	HKW,LKW,LKW,LKW,LMW,LMW,LMW,LMW,LMW,HKW,HKW,HKW 		\
}

#define RSC_LAYOUT_CARD_MC_THM_USR1_ATTR				\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW 		\
}

#define RSC_LAYOUT_CARD_LOAD_THM_USR1_ATTR				\
{									\
	HKW,HKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,HKW 		\
}

#define RSC_LAYOUT_CARD_IDLE_THM_USR1_ATTR				\
{									\
	HKW,HKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,HKW 		\
}

#define RSC_LAYOUT_CARD_RAM_THM_USR1_ATTR				\
{									\
	HKW,LMW,LMW,LMW,LMW,LMW,LKW,HKW,LMW,LMW,LKW,HKW 		\
}

#define RSC_LAYOUT_CARD_TASK_THM_USR1_ATTR				\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LMW,LMW,LMW,LMW,LMW,HKW 		\
}

#define RSC_SYSINFO_CPUID_COND0_THM_USR1_ATTR				\
{									\
	HWK,HWK,HWK,LWK,HDK,LMK,LMK,LMK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_CPUID_COND1_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,HDK,HDK,HDK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_CPUID_COND2_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_CPUID_COND3_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,\
	LWK,LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,\
	LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_SYSTEM_REGISTERS_COND0_THM_USR1_ATTR			\
{									\
	LWK,LWK,LWK,LWK 						\
}

#define RSC_SYSTEM_REGISTERS_COND1_THM_USR1_ATTR			\
{									\
	HDK,HDK,HDK,HDK 						\
}

#define RSC_SYSTEM_REGISTERS_COND2_THM_USR1_ATTR			\
{									\
	HWK,HWK,HWK,HWK 						\
}

#define RSC_SYSTEM_REGISTERS_COND3_THM_USR1_ATTR			\
{									\
	HDK,LMK,LMK,LMK 						\
}

#define RSC_SYSTEM_REGISTERS_COND4_THM_USR1_ATTR			\
{									\
	HDK,HDK,HDK,HDK 						\
}

#define RSC_SYSINFO_PROC_COND0_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 		\
}

#define RSC_SYSINFO_PROC_COND1_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,LWK,LWK 		\
}

#define RSC_SYSINFO_PROC_COND2_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK 		\
}

#define RSC_SYSINFO_PROC_COND3_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK 		\
}

#define RSC_SYSINFO_ISA_COND_0_0_THM_USR1_ATTR				\
{	/*	[N] & [N/N]	2*(0|0)+(0<<0)			*/	\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_0_1_THM_USR1_ATTR				\
{	/*	[Y]						*/	\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,HMK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_0_2_THM_USR1_ATTR				\
{	/*	[N/Y]	2*(0|1)+(0<<1)				*/	\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,HMK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_0_3_THM_USR1_ATTR				\
{	/*	[Y/N]	2*(1|0)+(1<<0)				*/	\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,HMK,LWK,LWK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_0_4_THM_USR1_ATTR				\
{	/*	[Y/Y]	2*(1|1)+(1<<1)				*/	\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,HMK,LWK,HMK,LWK					\
}

#define RSC_SYSINFO_ISA_COND_1_0_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_1_1_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,HMK,LWK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_1_2_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,HMK,LWK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_1_3_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,HMK,LWK,LWK,LWK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_1_4_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,HMK,LWK,HMK,LWK,LWK					\
}

#define RSC_SYSINFO_FEATURES_COND0_THM_USR1_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK 							\
}

#define RSC_SYSINFO_FEATURES_COND1_THM_USR1_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,			\
	LWK,LWK 							\
}

#define RSC_SYSINFO_FEATURES_COND2_THM_USR1_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LMK,LMK,LMK,LMK,LMK,LMK,LMK,			\
	LWK,LWK 							\
}

#define RSC_SYSINFO_FEATURES_COND3_THM_USR1_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,			\
	LWK,LWK 							\
}

#define RSC_SYSINFO_FEATURES_COND4_THM_USR1_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,			\
	LWK,LWK 							\
}

#define RSC_SYSINFO_TECH_COND0_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_TECH_COND1_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,HMK,HMK,HMK,LWK,LWK 			\
}

#define RSC_SYSINFO_PERFMON_COND0_THM_USR1_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK 						\
}

#define RSC_SYSINFO_PERFMON_COND1_THM_USR1_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HMK,			\
	HMK,HMK,LWK,LWK 						\
}

#define RSC_SYSINFO_PERFMON_COND2_THM_USR1_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,			\
	HWK,HWK,LWK,LWK 						\
}

#define RSC_SYSINFO_PERFMON_COND3_THM_USR1_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,HMK,HMK,HMK,HMK,HMK,			\
	HMK,HMK,LWK,LWK 						\
}

#define RSC_SYSINFO_PERFMON_COND4_THM_USR1_ATTR 			\
{									\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK 						\
}

#define RSC_SYSINFO_PERFMON_HWP_CAP_COND0_THM_USR1_ATTR 		\
{									\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK 			\
}

#define RSC_SYSINFO_PERFMON_HWP_CAP_COND1_THM_USR1_ATTR 		\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LMK,LMK,LMK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,HDK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,HDK,LWK,LWK,LWK,HDK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND0_THM_USR1_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND1_THM_USR1_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND2_THM_USR1_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LGK,LGK,LGK,LGK,LGK,LGK,LGK,LWK,LWK 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND3_THM_USR1_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,LWK,LWK 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND4_THM_USR1_ATTR			\
{									\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND5_THM_USR1_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND6_THM_USR1_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HWK,			\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_KERNEL_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 				\
}

#define RSC_TOPOLOGY_COND0_THM_USR1_ATTR				\
{									\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK		\
}

#define RSC_TOPOLOGY_COND1_THM_USR1_ATTR				\
{									\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK		\
}

#define RSC_TOPOLOGY_COND2_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK		\
}

#define RSC_TOPOLOGY_COND3_THM_USR1_ATTR				\
{									\
	LMK,LMK,LMK,HDK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK		\
}

#define RSC_TOPOLOGY_COND4_THM_USR1_ATTR				\
{									\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK		\
}

#define RSC_MEMORY_CONTROLLER_COND0_THM_USR1_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK						\
}

#define RSC_MEMORY_CONTROLLER_COND1_THM_USR1_ATTR			\
{									\
	HWK,HWK,HWK,HWK,HWK						\
}

#define RSC_CREATE_MENU_DISABLE_THM_USR1_ATTR				\
{									\
	HKM,HKM,HKM,HKM,HKM,HKM,HKM,HKM,HKM,HKM,HKM,HKM,		\
	HKM,HKM,HKM,HKM,HKM,HKM,HKM,HKM,HKM,HKM,HKM,HKM 		\
}

#define RSC_MENU_ITEM_MENU_THM_USR1_ATTR				\
{									\
	LKM,LKM,LKM,LKM,LKM,HKM,_LKM,_LKM,HKM,LKM,LKM,LKM,		\
	LKM,LKM,LKM,LKM,LKM,LKM, LKM, LKM,LKM,LKM,LKM,LKM		\
}

#define RSC_MENU_ITEM_VIEW_THM_USR1_ATTR				\
{									\
	LKM,LKM,LKM,LKM,LKM,HKM,_LKM,_LKM,HKM,LKM,LKM,LKM,		\
	LKM,LKM,LKM,LKM,LKM,LKM, LKM, LKM,LKM,LKM,LKM,LKM		\
}

#define RSC_MENU_ITEM_WINDOW_THM_USR1_ATTR				\
{									\
	LKM,LKM,LKM,LKM,HKM,_LKM,_LKM,HKM,LKM,LKM,LKM,LKM,		\
	LKM,LKM,LKM,LKM,LKM, LKM, LKM,LKM,LKM,LKM,LKM,LKM		\
}

#define RSC_CREATE_MENU_FN_KEY_THM_USR1_ATTR				\
{									\
	LKM,LKM,LKM,LKM,LKM,LKM,LKM,LKM, LKM,LKM,LKM,LKM,		\
	LKM,LKM,LKM,LKM,LKM,LKM,LKM,HKM,_LKM,_LKM,HKM,LKM		\
}

#define RSC_CREATE_MENU_SHORTKEY_THM_USR1_ATTR				\
{									\
	LKM,LKM,LKM,LKM,LKM,LKM,LKM,LKM,LKM, LKM,LKM,LKM,		\
	LKM,LKM,LKM,LKM,LKM,LKM,LKM,LKM,HKM,_LKM,HKM,LKM		\
}

#define RSC_CREATE_MENU_CTRL_KEY_THM_USR1_ATTR				\
{									\
	LKM,LKM, LKM, LKM, LKM, LKM,LKM,LKM,LKM, LKM,LKM,LKM,		\
	LKM,HKM,_LKM,_LKM,_LKM,_LKM,HKM,HKM,HKM,_LKM,HKM,LKM		\
}

#define RSC_CREATE_SETTINGS_COND0_THM_USR1_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,HDK,LWK \
}

#define RSC_CREATE_SETTINGS_COND1_THM_USR1_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,HMK,HMK,HMK,HDK,LWK \
}

#define RSC_CREATE_ADV_HELP_COND0_THM_USR1_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 				\
}

#define RSC_CREATE_ADV_HELP_COND1_THM_USR1_ATTR 			\
{									\
	LWK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,			\
	HCK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 				\
}

#define RSC_CREATE_HOTPLUG_CPU_ENABLE_THM_USR1_ATTR			\
{									\
	LWK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,LWK,LDK,LDK,LDK	\
}

#define RSC_CREATE_HOTPLUG_CPU_DISABLE_THM_USR1_ATTR			\
{									\
	LWK,LMK,LMK,LMK,LMK,LMK,LMK,LMK,LMK,LMK,LMK,LWK,LDK,LDK,LDK	\
}

#define RSC_CREATE_HOTPLUG_CPU_ONLINE_THM_USR1_ATTR			\
{									\
	LMK,LMK,LMK,LMK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK	\
}

#define RSC_CREATE_HOTPLUG_CPU_OFFLINE_THM_USR1_ATTR			\
{									\
	HDK,HDK,HDK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND0_THM_USR1_ATTR			\
{									\
	LWK,HWK,HWK,HWK,HWK,LWK,HWK,HWK,LWK,HDK,HDK,HDK,LWK,LWK,	\
	LWK,LWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND1_THM_USR1_ATTR			\
{									\
	LWK,HBK,HBK,HBK,HBK,LBK,HBK,HBK,LWK,HDK,HDK,HDK,LWK,LWK,	\
	LWK,LWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND2_THM_USR1_ATTR			\
{									\
	LWK,HRK,HRK,HRK,HRK,LRK,HRK,HRK,LWK,HDK,HDK,HDK,LWK,LWK,	\
	LWK,LWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND3_THM_USR1_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,	\
	LWK,LWK,HMK,HMK,HMK,HMK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND4_THM_USR1_ATTR			\
{									\
	LWK,HWK,HWK,HWK,HWK,LWK,HWK,HWK,LWK,HDK,HDK,HDK,LWK,LWK,	\
	LWK,LWK,HMK,HMK,HMK,HMK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND5_THM_USR1_ATTR			\
{									\
	LWK,HBK,HBK,HBK,HBK,LBK,HBK,HBK,LWK,HDK,HDK,HDK,LWK,LWK,	\
	LWK,LWK,HMK,HMK,HMK,HMK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND6_THM_USR1_ATTR			\
{									\
	LWK,HRK,HRK,HRK,HRK,LRK,HRK,HRK,LWK,HDK,HDK,HDK,LWK,LWK,	\
	LWK,LWK,HMK,HMK,HMK,HMK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_SELECT_CPU_COND0_THM_USR1_ATTR			\
{									\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,		\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,		\
	HDK,LWK,HDK,HDK,HDK,LWK,HDK,HDK,HDK,HDK 			\
}

#define RSC_CREATE_SELECT_CPU_COND1_THM_USR1_ATTR			\
{									\
	LMK,LMK,LMK,LMK,LMK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,		\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,		\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_CREATE_SELECT_CPU_COND2_THM_USR1_ATTR			\
{									\
	LMK,LMK,LMK,LMK,LMK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,		\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,		\
	LWK,LWK,HRK,HRK,HRK,LWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_HOT_EVENT_COND0_THM_USR1_ATTR				\
{									\
	HKW,HKW,HKW							\
}

#define RSC_HOT_EVENT_COND1_THM_USR1_ATTR				\
{									\
	HRW,HRW,HRW							\
}

#define RSC_HOT_EVENT_COND2_THM_USR1_ATTR				\
{									\
	{.fg=CYAN,.bg=WHITE,.bf=1,.un=1},				\
	{.fg=CYAN,.bg=WHITE,.bf=0,.un=0},				\
	{.fg=CYAN,.bg=WHITE,.bf=0,.un=0}				\
}

#define RSC_HOT_EVENT_COND3_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW							\
}

#define RSC_HOT_EVENT_COND4_THM_USR1_ATTR				\
{									\
	{.fg=CYAN,.bg=MAGENTA,.bf=0,.un=1},				\
	{.fg=CYAN,.bg=MAGENTA,.bf=0,.un=0},				\
	{.fg=CYAN,.bg=MAGENTA,.bf=0,.un=0}				\
}

#define RSC_BOX_EVENT_COND00_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK \
}

#define RSC_BOX_EVENT_COND01_THM_USR1_ATTR				\
{									\
	LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,HDK \
}

#define RSC_BOX_EVENT_COND10_THM_USR1_ATTR				\
{									\
	LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,HDK \
}

#define RSC_BOX_EVENT_COND11_THM_USR1_ATTR				\
{									\
	LKY,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LKY,HDK \
}

#define RSC_BOX_EVENT_BUTTON_THM_USR1_ATTR				\
{									\
	LWK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,LWK \
}

#define RSC_CREATE_RECORDER_THM_USR1_ATTR				\
{									\
	LWK,LWK,LWK,LWK,HDK,LWK,LWK,HDK,LWK,LWK,LWK,LWK 		\
}

#define RSC_SMBIOS_ITEM_THM_USR1_ATTR					\
{									\
	HDK,LMK,LMK,HDK,HDK,						\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_CREATE_SELECT_FREQ_PKG_THM_USR1_ATTR			\
{									\
	HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,HMK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HMK,HMK,HMK,HMK,HMK,HMK,\
	HMK,HMK,HDK,HDK,HDK,LWK,LWK,HMK,HMK,HMK,HMK,HMK,LWK,LWK 	\
}

#define RSC_CREATE_SELECT_FREQ_COND0_THM_USR1_ATTR			\
{									\
	LMK,LMK,LMK,LMK,LMK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,		\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,		\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,HDK,HDK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK				\
}

#define RSC_CREATE_SELECT_FREQ_COND1_THM_USR1_ATTR			\
{									\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,		\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,		\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK				\
}

_Static_assert( __builtin_strlen(RSC_THEME_USR1_CODE)
	==	__builtin_strlen(RSC_BOX_THEME_BLANK_CODE),
"Mandatory string length");
