/*
 * CoreFreq
 * Copyright (C) 2015-2021 CYRIL INGENIERIE
 * Licenses: GPL2
 */

#define RSC_UI_THM_USR1_ATTR						\
{									\
	[UI_LAYOUT_HEADER_PROC_BRAND] = {				\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_HEADER_PROC_BRAND_FILL] = {				\
		.fg = WHITE, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_HEADER_ARCHITECTURE] = {				\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_HEADER_ARCH_FILL] = {				\
		.fg = WHITE, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_HEADER_BCLK_FILL] = {				\
		.fg = WHITE, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_RULER_INSTRUCTIONS] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_CYCLES] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_CSTATES] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_INTERRUPTS] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_PACKAGE] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_TASKS_FILL] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_TASKS_TRACKING] = {				\
		.fg = CYAN, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_ENERGY] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_SLICE] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_ENABLE_0] =  {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_ENABLE_1] =  {				\
		.fg = GREEN, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_ENABLE_2] =  {				\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_TSC_NONE] =  {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_TSC_VAR] = {					\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_TSC_INV] = {					\
		.fg = GREEN, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_TM_0] = {					\
		.fg = WHITE, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_TM_1] = {					\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_TM_2] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_TM_3] = {					\
		.fg = GREEN, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_FILL] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_GATE] = {					\
		.fg = CYAN, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_SPACE] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_LEFT_BRACE] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_RIGHT_BRACE] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_KERNEL_VERSION] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_UNMAP_GATE] = {				\
		.fg = RED, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_DMI_STRING] = {				\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_BCLK_TO_VIEW] = {					\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_ROW_CPU_OFFLINE] =  {				\
		.fg = WHITE, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_LOAD_TAB_DIM] = {				\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_LOAD_TAB_BRIGHT] = {				\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_ILLUMINATES_CPU_OFF] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_ILLUMINATES_CPU_ON] = {					\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_ILLUMINATES_CPU_SP] = {					\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_DRAW_FREQUENCY_LOAD_CLEAR] = {				\
		.fg = WHITE, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_FREQUENCY_LOAD_LOW] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_FREQUENCY_LOAD_MEDIUM] = {				\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_FREQUENCY_LOAD_HIGH] = {				\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_DRAW_ALTMONITOR_TASKS_CLEAR] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_ALTMONITOR_TASKS_SPACE] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_MONITOR_FREQUENCY_NOMINAL] =  {			\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_MONITOR_FREQUENCY_LOW] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_DRAW_MONITOR_FREQUENCY_HIGH] = {				\
		.fg = RED, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_MONITOR_FREQUENCY_HOT] = {				\
		.fg = MAGENTA, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_CARD_CORE_OFFLINE] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_CARD_RAM_2DIGITS] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_LAYOUT_CARD_RAM_3DIGITS] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_CARD_CORE_NOMINAL] =  {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_CARD_CORE_LOW] = {					\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_CARD_CORE_MEDIUM] = {					\
		.fg = BLUE, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_DRAW_CARD_CORE_HIGH] = {					\
		.fg = RED, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_DRAW_CARD_TASK_FILL] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_WIN_MENU_SELECT] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_WIN_MENU_TITLE_UNFOCUS] =  {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_WIN_MENU_TITLE_FOCUS] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_WIN_SORT_BY_FIELD_TITLE] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_WIN_TRACKING_CHILD_PROCESS] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_WIN_TRACKING_TITLE] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_WIN_HOT_PLUG_CPU_TITLE] =  {				\
		.fg = WHITE, .un = 0, .bg = BLUE, .bf = 1		\
	},								\
	[UI_WIN_SELECT_IDLE_RESET] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_SELECT_IDLE_POLL] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_SELECT_IDLE_CURRENT] = {				\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_POPUP_MSG_ITEM] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_POPUP_MSG_SELECT_UNFOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_POPUP_MSG_SELECT_FOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_POPUP_MSG_BORDER_UNFOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = RED, .bf = 0		\
	},								\
	[UI_WIN_POPUP_MSG_BORDER_FOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = RED, .bf = 1		\
	},								\
	[UI_WIN_POPUP_MSG_TITLE_UNFOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = RED, .bf = 0		\
	},								\
	[UI_WIN_POPUP_MSG_TITLE_FOCUS] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_WIN_EXIT_ISSUE_RECORDER] = {				\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_ISSUE_STRESS] = {					\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_ISSUE_OS_CPU_IDLE] = {				\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_HEADER] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_EXIT_BLANK] =  {					\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_CONFIRM] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_FOOTER] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_BOX_DISABLE_STATE] = {					\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_BOX_ENABLE_STATE] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_BOX_BLANK] = {						\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_BOX_DESC] = {						\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_BOX_INTERVAL] = {						\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_BOX_EXPERIMENTAL_NOMINAL] = {				\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_BOX_EXPERIMENTAL_WARNING] = {				\
		.fg = RED, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_DROP_IDLE_ROUTE] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_BOX_TOOLS_STOP] =  {					\
		.fg = RED, .un = 0, .bg = BLACK, .bf = 1		\
	}								\
}

#define RSC_VOID_THM_USR1_ATTR						\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_RUN_STATE_COLOR_THM_USR1_ATTR	\
{						\
	HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,	\
	HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,	\
	HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,	\
	HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,	\
	HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW 	\
}

#define RSC_UNINT_STATE_COLOR_THM_USR1_ATTR	\
{						\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,	\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,	\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,	\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,	\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW 	\
}

#define RSC_ZOMBIE_STATE_COLOR_THM_USR1_ATTR	\
{						\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW,	\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW,	\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW,	\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW,	\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW 	\
}

#define RSC_SLEEP_STATE_COLOR_THM_USR1_ATTR	\
{						\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,	\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,	\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,	\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,	\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW 	\
}

#define RSC_WAIT_STATE_COLOR_THM_USR1_ATTR	\
{						\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,	\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,	\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,	\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,	\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW 	\
}

#define RSC_OTHER_STATE_COLOR_THM_USR1_ATTR	\
{						\
	LGW,LGW,LGW,LGW,LGW,LGW,LGW,LGW,	\
	LGW,LGW,LGW,LGW,LGW,LGW,LGW,LGW,	\
	LGW,LGW,LGW,LGW,LGW,LGW,LGW,LGW,	\
	LGW,LGW,LGW,LGW,LGW,LGW,LGW,LGW,	\
	LGW,LGW,LGW,LGW,LGW,LGW,LGW,LGW 	\
}

#define RSC_TRACKER_STATE_COLOR_THM_USR1_ATTR	\
{						\
	LKC,LKC,LKC,LKC,LKC,LKC,LKC,LKC,	\
	LKC,LKC,LKC,LKC,LKC,LKC,LKC,LKC,	\
	LKC,LKC,LKC,LKC,LKC,LKC,LKC,LKC,	\
	LKC,LKC,LKC,LKC,LKC,LKC,LKC,LKC,	\
	LKC,LKC,LKC,LKC,LKC,LKC,LKC,LKC 	\
}

#define RSC_LAYOUT_HEADER_PROC_THM_USR1_ATTR				\
{									\
	HRW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW 		\
}

#define RSC_LAYOUT_HEADER_CPU_THM_USR1_ATTR				\
{									\
	HKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,HKW,HKW,HKW		\
}

#define RSC_LAYOUT_HEADER_ARCH_THM_USR1_ATTR				\
{									\
	HCW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW	\
}

#define RSC_LAYOUT_HEADER_CACHE_L1_THM_USR1_ATTR			\
{									\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,				\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,LKW,LKW,LKW,			\
	HKW,HKW,HKW,HKW,HKW,LKW,LKW,LKW,HKW,HKW 			\
}

#define RSC_LAYOUT_HEADER_BCLK_THM_USR1_ATTR				\
{									\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,		\
	HBW,HBW,HBW,HBW,HBW,HKW,HBW,HBW,HBW,HKW,HBW,HBW,HBW,HKW,HKW,HKW \
}

#define RSC_LAYOUT_HEADER_CACHES_THM_USR1_ATTR				\
{									\
	HKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,			\
	HKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW			\
}

#define RSC_LAYOUT_RULER_LOAD_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,_HCW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_VAR_LOAD_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW 							\
}

#define RSC_LAYOUT_RULER_REL_LOAD_THM_USR1_ATTR \
	RSC_LAYOUT_RULER_VAR_LOAD_THM_USR1_ATTR

#define RSC_LAYOUT_RULER_ABS_LOAD_THM_USR1_ATTR \
	RSC_LAYOUT_RULER_VAR_LOAD_THM_USR1_ATTR

#define RSC_LAYOUT_MONITOR_FREQUENCY_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	HKW,HKW,HKW,HKW,HKW,HKW,LKW,LKW,LKW,HKW,LRW,LRW,LRW		\
}

#define RSC_LAYOUT_MONITOR_INST_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW		\
}

#define RSC_LAYOUT_MONITOR_COMMON_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW		\
}

#define RSC_LAYOUT_MONITOR_TASKS_THM_USR1_ATTR				\
{									\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_MONITOR_SLICE_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HRW,HRW,HRW,\
	HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW,HRW	\
}

#define RSC_LAYOUT_RULER_FREQUENCY_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_FREQUENCY_AVG_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,HKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_FREQUENCY_PKG_THM_USR1_ATTR			\
{									\
	_HCW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_INST_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_CYCLES_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_CSTATES_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_INTERRUPTS_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_PACKAGE_THM_USR1_ATTR	RSC_VOID_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,\
	HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW,HBW \
}

#define RSC_LAYOUT_PACKAGE_PC02_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC03_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC04_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC06_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC07_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC08_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC09_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_PC10_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_MC06_THM_USR1_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR1_ATTR

#define RSC_LAYOUT_PACKAGE_UNCORE_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,HKW,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_TASKS_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LDK,LDK,LDK,LDK,LDK,LDK,LDK,LDK,LDK,\
	LDK,LDK,LDK,LDK,LDK,LDK,LDK,LDK,LDK,LDK,LDK,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_TASKS_STATE_SORTED_THM_USR1_ATTR			\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,			\
	LKW,LCW,LCW,LCW,LCW,LCW,HKW,LKW, LKW,LKW,LKW			\
}

#define RSC_LAYOUT_TASKS_RUNTIME_SORTED_THM_USR1_ATTR			\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,			\
	LKW,LCW,LCW,LCW,LCW,LCW,LCW,LCW, HKW,LKW,LKW			\
}

#define RSC_LAYOUT_TASKS_USRTIME_SORTED_THM_USR1_ATTR			\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,			\
	LKW,LCW,LCW,LCW,LCW,LCW,LCW,LCW, LCW,HKW,LKW			\
}

#define RSC_LAYOUT_TASKS_SYSTIME_SORTED_THM_USR1_ATTR			\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,			\
	LKW,LCW,LCW,LCW,LCW,LCW,LCW,LCW, HKW,LKW,LKW			\
}

#define RSC_LAYOUT_TASKS_PROCESS_SORTED_THM_USR1_ATTR			\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,			\
	LKW,LCW,LCW,LCW,HKW,LKW,LKW,LKW, LKW,LKW,LKW			\
}

#define RSC_LAYOUT_TASKS_COMMAND_SORTED_THM_USR1_ATTR			\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,			\
	LKW,LCW,LCW,LCW,LCW,LCW,LCW,LCW, HKW,LKW,LKW			\
}

#define RSC_LAYOUT_TASKS_REVERSE_SORT_OFF_THM_USR1_ATTR 		\
{									\
	LKW,LKW,LKW,LKW,LKW,_HCW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW	\
}

#define RSC_LAYOUT_TASKS_REVERSE_SORT_ON_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,_HCW,LKW,LKW,LKW,HKW,LCW,LCW,LCW,HKW,LKW	\
}

#define RSC_LAYOUT_TASKS_VALUE_SWITCH_THM_USR1_ATTR			\
{									\
	LKW,_HCW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW		\
}

#define RSC_LAYOUT_TASKS_VALUE_OFF_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW							\
}

#define RSC_LAYOUT_TASKS_VALUE_ON_THM_USR1_ATTR 			\
{									\
	LCW,LCW,LCW							\
}

#define RSC_LAYOUT_TASKS_TRACKING_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,_HCW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW					\
}

#define RSC_LAYOUT_RULER_SENSORS_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_PWR_DOMAIN_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,\
	LKW,LKW,HKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,\
	LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_PWR_UNCORE_THM_USR1_ATTR	\
	RSC_LAYOUT_RULER_PWR_DOMAIN_THM_USR1_ATTR

#define RSC_LAYOUT_RULER_PWR_PLATFORM_THM_USR1_ATTR	\
	RSC_LAYOUT_RULER_PWR_DOMAIN_THM_USR1_ATTR

#define RSC_LAYOUT_RULER_PWR_SOC_THM_USR1_ATTR		\
	RSC_LAYOUT_RULER_PWR_DOMAIN_THM_USR1_ATTR

#define RSC_LAYOUT_RULER_VOLTAGE_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_VPKG_SOC_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,HKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_ENERGY_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_RULER_POWER_THM_USR1_ATTR	\
	RSC_LAYOUT_RULER_ENERGY_THM_USR1_ATTR

#define RSC_LAYOUT_RULER_SLICE_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_LAYOUT_FOOTER_TECH_X86_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,LKW 	\
}

#define RSC_LAYOUT_FOOTER_TECH_INTEL_THM_USR1_ATTR			\
{									\
	HKW,HKW,HKW,LKW,HKW,HKW,HKW,HKW,LKW,HKW,HKW,HKW,LKW,		\
	HKW,HKW,HKW,HKW,HKW,LKW,HKW,HKW,HKW,LKW,			\
	HKW,HKW,HKW,LKW,HKW,HKW,HKW,LKW,HKW,HKW,HKW,LKW,		\
	HKW,HKW,LKW,HKW,HKW,HKW,HKW,LKW,				\
	HKW,HKW,LKW,HKW,HKW,HKW,HKW,HKW,				\
	LKW,HKW,HWK,HWK,HWK,HWK,HKW,HKW,LKW,HKW,HKW,HKW,HKW,LKW,HKW 	\
}

#define RSC_LAYOUT_FOOTER_TECH_AMD_THM_USR1_ATTR			\
{									\
	HKW,HKW,HKW,LKW,HKW,HKW,HKW,LKW,HKW,HKW,HKW,LKW,		\
	HKW,HKW,HKW,HKW,HKW,LKW,HKW,HKW,HKW,LKW,HKW,HKW,HKW,		\
	LKW,HKW,HKW,HKW,LKW,HKW,HKW,HKW,LKW,HKW,HKW,HKW,LKW,		\
	HKW,HKW,HKW,LKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,		\
	LKW,HKW,LKW,LKW,LKW,LKW,HKW,HKW,LKW,HKW,LKW,LKW,LKW,LKW,HKW 	\
}

#define RSC_LAYOUT_FOOTER_SYSTEM_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,	\
	LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,	\
	LKW,HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW 	\
}

#define RSC_LAYOUT_CARD_CORE_ONLINE_THM_USR1_ATTR			\
{									\
	HKW,HKW,LCW,LCW,LCW,HKW,HKW,HKW,HKW,HKW,HKW,HKW 		\
}

#define RSC_LAYOUT_CARD_CORE_ONLINE_COND0_THM_USR1_ATTR \
	RSC_LAYOUT_CARD_CORE_ONLINE_THM_USR1_ATTR

#define RSC_LAYOUT_CARD_CORE_ONLINE_COND1_THM_USR1_ATTR \
	RSC_LAYOUT_CARD_CORE_ONLINE_THM_USR1_ATTR

#define RSC_LAYOUT_CARD_CORE_OFFLINE_THM_USR1_ATTR			\
{									\
	HKW,HKW,LBK,LBK,LBK,HKW,HKW,LKW,LKW,LKW,HKW,HKW 		\
}

#define RSC_LAYOUT_CARD_CLK_THM_USR1_ATTR				\
{									\
	HKW,HKW,HWK,HWK,HWK,LKW,HWK,HKW,HKW,HKW,HKW,HKW 		\
}

#define RSC_LAYOUT_CARD_UNCORE_THM_USR1_ATTR				\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,LCW,LCW,HKW 		\
}

#define RSC_LAYOUT_CARD_BUS_THM_USR1_ATTR				\
{									\
	HKW,LKW,LKW,LKW,HWK,HWK,HWK,HWK,HWK,HKW,HKW,HKW 		\
}

#define RSC_LAYOUT_CARD_MC_THM_USR1_ATTR				\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW 		\
}

#define RSC_LAYOUT_CARD_LOAD_THM_USR1_ATTR				\
{									\
	HKW,HKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,HKW 		\
}

#define RSC_LAYOUT_CARD_IDLE_THM_USR1_ATTR				\
{									\
	HKW,HKW,HKW,HKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,HKW 		\
}

#define RSC_LAYOUT_CARD_RAM_THM_USR1_ATTR				\
{									\
	HKW,HWK,HWK,HWK,HWK,HWK,LKW,HKW,HWK,HWK,LDK,HKW 		\
}

#define RSC_LAYOUT_CARD_TASK_THM_USR1_ATTR				\
{									\
	HKW,LKW,LKW,LKW,LKW,LKW,HWK,HWK,HWK,HWK,HWK,HKW 		\
}

#define RSC_SYSINFO_CPUID_COND0_THM_USR1_ATTR				\
{									\
	HWK,HWK,HWK,LKW,HKW,LCW,LCW,LCW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW 			\
}

#define RSC_SYSINFO_CPUID_COND1_THM_USR1_ATTR				\
{									\
	HBK,HBK,HBK,HBK,HBK,LBK,LBK,LBK,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW 			\
}

#define RSC_SYSINFO_CPUID_COND2_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW 			\
}

#define RSC_SYSINFO_CPUID_COND3_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LKW,\
	LKW,LKW,LKW,LKW,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LKW,LKW,LKW,LKW,\
	LKW,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LKW,LKW,LKW,LKW,LKW,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,LKW,LKW,LKW,LKW 			\
}

#define RSC_SYSTEM_REGISTERS_COND0_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW 						\
}

#define RSC_SYSTEM_REGISTERS_COND1_THM_USR1_ATTR			\
{									\
	HBK,HBK,HBK,HBK 						\
}

#define RSC_SYSTEM_REGISTERS_COND2_THM_USR1_ATTR			\
{									\
	HWK,HWK,HWK,HWK 						\
}

#define RSC_SYSTEM_REGISTERS_COND3_THM_USR1_ATTR			\
{									\
	HKW,LCW,LCW,LCW 						\
}

#define RSC_SYSTEM_REGISTERS_COND4_THM_USR1_ATTR			\
{									\
	HKW,LBK,LBK,LBK 						\
}

#define RSC_SYSINFO_PROC_COND0_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW 		\
}

#define RSC_SYSINFO_PROC_COND1_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,HGK,HGK,HGK,HGK,HGK,HGK,HGK,LKW,LKW 		\
}

#define RSC_SYSINFO_PROC_COND2_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LKW,LKW 		\
}

#define RSC_SYSINFO_PROC_COND3_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,HWK,HWK,HWK,HWK,HWK,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LKW,LKW 		\
}

#define RSC_SYSINFO_ISA_COND_0_0_THM_USR1_ATTR				\
{	/*	[N] & [N/N]	2*(0|0)+(0<<0)			*/	\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW					\
}
#define RSC_SYSINFO_ISA_COND_0_1_THM_USR1_ATTR				\
{	/*	[Y]						*/	\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,HGK,LKW					\
}
#define RSC_SYSINFO_ISA_COND_0_2_THM_USR1_ATTR				\
{	/*	[N/Y]	2*(0|1)+(0<<1)				*/	\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,HGK,LKW					\
}
#define RSC_SYSINFO_ISA_COND_0_3_THM_USR1_ATTR				\
{	/*	[Y/N]	2*(1|0)+(1<<0)				*/	\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,HGK,LKW,LKW,LKW					\
}
#define RSC_SYSINFO_ISA_COND_0_4_THM_USR1_ATTR				\
{	/*	[Y/Y]	2*(1|1)+(1<<1)				*/	\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,HGK,LKW,HGK,LKW					\
}

#define RSC_SYSINFO_ISA_COND_1_0_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW					\
}
#define RSC_SYSINFO_ISA_COND_1_1_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,HGK,LKW,LKW					\
}
#define RSC_SYSINFO_ISA_COND_1_2_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,HGK,LKW,LKW					\
}
#define RSC_SYSINFO_ISA_COND_1_3_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,HGK,LKW,LKW,LKW,LKW					\
}
#define RSC_SYSINFO_ISA_COND_1_4_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,HGK,LKW,HGK,LKW,LKW					\
}

#define RSC_SYSINFO_FEATURES_COND0_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW 							\
}

#define RSC_SYSINFO_FEATURES_COND1_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,HBK,HBK,HBK,HBK,HBK,HBK,HBK,			\
	LKW,LKW 							\
}

#define RSC_SYSINFO_FEATURES_COND2_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LCW,LCW,LCW,LCW,LCW,LCW,LCW,			\
	LKW,LKW 							\
}

#define RSC_SYSINFO_FEATURES_COND3_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,HGK,HGK,HGK,HGK,HGK,HGK,HGK,			\
	LKW,LKW 							\
}

#define RSC_SYSINFO_FEATURES_COND4_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,HGK,HGK,HGK,HGK,HGK,HGK,HGK,HGK,HGK,			\
	LKW,LKW 							\
}

#define RSC_SYSINFO_TECH_COND0_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW 			\
}

#define RSC_SYSINFO_TECH_COND1_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,HGK,HGK,HGK,LKW,LKW 			\
}

#define RSC_SYSINFO_PERFMON_COND0_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW 						\
}

#define RSC_SYSINFO_PERFMON_COND1_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HGK,			\
	HGK,HGK,LKW,LKW 						\
}

#define RSC_SYSINFO_PERFMON_COND2_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,HBK,HBK,HBK,HBK,HBK,			\
	HBK,HBK,LKW,LKW 						\
}

#define RSC_SYSINFO_PERFMON_COND3_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,HGK,HGK,HGK,HGK,HGK,			\
	HGK,HGK,LKW,LKW 						\
}

#define RSC_SYSINFO_PERFMON_COND4_THM_USR1_ATTR 			\
{									\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,			\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,			\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,			\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,			\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,			\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,			\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,			\
	HKW,HKW,HKW,HKW 						\
}

#define RSC_SYSINFO_PERFMON_HWP_CAP_COND0_THM_USR1_ATTR 		\
{									\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW 		\
}

#define RSC_SYSINFO_PERFMON_HWP_CAP_COND1_THM_USR1_ATTR 		\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW 		\
}

#define RSC_SYSINFO_PWR_THERMAL_COND0_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND1_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,HBK,HBK,HBK,HBK,HBK,HBK,HBK,LKW,LKW 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND2_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LGW,LGW,LGW,LGW,LGW,LGW,LGW,LKW,LKW 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND3_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,HGK,HGK,HGK,HGK,HGK,HGK,HGK,LKW,LKW 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND4_THM_USR1_ATTR			\
{									\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,			\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,			\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,			\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,			\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND5_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,HWK,HWK,HWK,HWK,HWK,HWK,LKW,LKW,LKW 			\
}

#define RSC_SYSINFO_KERNEL_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW 				\
}

#define RSC_TOPOLOGY_COND0_THM_USR1_ATTR				\
{									\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK		\
}

#define RSC_TOPOLOGY_COND1_THM_USR1_ATTR				\
{									\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK		\
}

#define RSC_TOPOLOGY_COND2_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW		\
}

#define RSC_TOPOLOGY_COND3_THM_USR1_ATTR				\
{									\
	LCW,LCW,LCW,HKW,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK		\
}

#define RSC_TOPOLOGY_COND4_THM_USR1_ATTR				\
{									\
	LBK,LBK,LBK,HKW,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK		\
}

#define RSC_MEMORY_CONTROLLER_COND0_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW						\
}

#define RSC_MEMORY_CONTROLLER_COND1_THM_USR1_ATTR			\
{									\
	HWK,HWK,HWK,HWK,HWK						\
}

#define RSC_CREATE_MENU_DISABLE_THM_USR1_ATTR				\
{									\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,		\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW 		\
}

#define RSC_MENU_ITEM_MENU_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,HKW,_LKW,_LKW,HKW,LKW,LKW,LKW,		\
	LKW,LKW,LKW,LKW,LKW,LKW, LKW, LKW,LKW,LKW,LKW,LKW		\
}

#define RSC_MENU_ITEM_VIEW_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,HKW,_LKW,_LKW,HKW,LKW,LKW,LKW,		\
	LKW,LKW,LKW,LKW,LKW,LKW, LKW, LKW,LKW,LKW,LKW,LKW		\
}

#define RSC_MENU_ITEM_WINDOW_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,HKW,_LKW,_LKW,HKW,LKW,LKW,LKW,LKW,		\
	LKW,LKW,LKW,LKW,LKW, LKW, LKW,LKW,LKW,LKW,LKW,LKW		\
}

#define RSC_CREATE_MENU_FN_KEY_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW, LKW,LKW,LKW,LKW,		\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,_LKW,_LKW,HKW,LKW		\
}

#define RSC_CREATE_MENU_SHORTKEY_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW, LKW,LKW,LKW,		\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,_LKW,HKW,LKW		\
}

#define RSC_CREATE_MENU_CTRL_KEY_THM_USR1_ATTR				\
{									\
	LKW,LKW, LKW, LKW, LKW, LKW,LKW,LKW,LKW, LKW,LKW,LKW,		\
	LKW,HKW,_LKW,_LKW,_LKW,_LKW,HKW,HKW,HKW,_LKW,HKW,LKW		\
}

#define RSC_CREATE_SETTINGS_COND0_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,LKW,LKW,LKW,HKW,LKW \
}

#define RSC_CREATE_SETTINGS_COND1_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HGK,HGK,HGK,HKW,LKW \
}

#define RSC_CREATE_ADV_HELP_COND0_THM_USR1_ATTR 			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW 				\
}

#define RSC_CREATE_ADV_HELP_COND1_THM_USR1_ATTR 			\
{									\
	LKW,HCK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,			\
	HCK,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW 				\
}

#define RSC_CREATE_HOTPLUG_CPU_ENABLE_THM_USR1_ATTR			\
{									\
	LKW,LGW,LGW,LGW,LGW,LGW,LGW,LGW,LGW,LGW,LGW,LKW,LDK,LDK,LDK	\
}

#define RSC_CREATE_HOTPLUG_CPU_DISABLE_THM_USR1_ATTR			\
{									\
	LKW,LCW,LCW,LCW,LCW,LCW,LCW,LCW,LCW,LCW,LCW,LKW,LDK,LDK,LDK	\
}

#define RSC_CREATE_HOTPLUG_CPU_ONLINE_THM_USR1_ATTR			\
{									\
	LCW,LCW,LCW,LCW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW	\
}

#define RSC_CREATE_HOTPLUG_CPU_OFFLINE_THM_USR1_ATTR			\
{									\
	LBK,LBK,LBK,LBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND0_THM_USR1_ATTR			\
{									\
	LKW,HWK,HWK,HWK,HWK,LKW,HWK,HWK,LKW,HKW,HKW,HKW,LKW,LKW,	\
	LKW,LKW,HWK,HWK,HWK,HWK,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW	\
}

#define RSC_CREATE_RATIO_CLOCK_COND1_THM_USR1_ATTR			\
{									\
	LKW,HBK,HBK,HBK,HBK,LBK,HBK,HBK,LKW,HKW,HKW,HKW,LKW,LKW,	\
	LKW,LKW,HWK,HWK,HWK,HWK,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW	\
}

#define RSC_CREATE_RATIO_CLOCK_COND2_THM_USR1_ATTR			\
{									\
	LKW,HRK,HRK,HRK,HRK,LRK,HRK,HRK,LKW,HKW,HKW,HKW,LKW,LKW,	\
	LKW,LKW,HWK,HWK,HWK,HWK,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW	\
}

#define RSC_CREATE_RATIO_CLOCK_COND3_THM_USR1_ATTR			\
{									\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,	\
	LKW,LKW,HCK,HCK,HCK,HCK,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW	\
}

#define RSC_CREATE_RATIO_CLOCK_COND4_THM_USR1_ATTR			\
{									\
	LKW,HWK,HWK,HWK,HWK,LKW,HWK,HWK,LKW,HKW,HKW,HKW,LKW,LKW,	\
	LKW,LKW,HCK,HCK,HCK,HCK,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW	\
}

#define RSC_CREATE_RATIO_CLOCK_COND5_THM_USR1_ATTR			\
{									\
	LKW,HBK,HBK,HBK,HBK,LBK,HBK,HBK,LKW,HKW,HKW,HKW,LKW,LKW,	\
	LKW,LKW,HCK,HCK,HCK,HCK,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW	\
}

#define RSC_CREATE_RATIO_CLOCK_COND6_THM_USR1_ATTR			\
{									\
	LKW,HRK,HRK,HRK,HRK,LRK,HRK,HRK,LKW,HKW,HKW,HKW,LKW,LKW,	\
	LKW,LKW,HCK,HCK,HCK,HCK,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW	\
}

#define RSC_CREATE_SELECT_CPU_COND0_THM_USR1_ATTR			\
{									\
	LBK,LBK,LBK,LBK,LBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,		\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,		\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK 			\
}

#define RSC_CREATE_SELECT_CPU_COND1_THM_USR1_ATTR			\
{									\
	LCW,LCW,LCW,LCW,LCW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,		\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,		\
	LKW,LKW,LCW,LCW,LCW,LKW,LKW,LKW,LKW,LKW 			\
}

#define RSC_CREATE_SELECT_CPU_COND2_THM_USR1_ATTR			\
{									\
	LCW,LCW,LCW,LCW,LCW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,		\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,		\
	LKW,LKW,HRK,HRK,HRK,LKW,LKW,LKW,LKW,LKW 			\
}

#define RSC_HOT_EVENT_COND0_THM_USR1_ATTR				\
{									\
	HKW,HKW,HKW							\
}

#define RSC_HOT_EVENT_COND1_THM_USR1_ATTR				\
{									\
	HRK,HRK,HRK							\
}

#define RSC_HOT_EVENT_COND2_THM_USR1_ATTR				\
{									\
	{.fg=CYAN,.bg=BLACK,.bf=1,.un=1},				\
	{.fg=CYAN,.bg=BLACK,.bf=0,.un=0},				\
	{.fg=CYAN,.bg=BLACK,.bf=0,.un=0}				\
}

#define RSC_HOT_EVENT_COND3_THM_USR1_ATTR				\
{									\
	HWK,HWK,HWK							\
}

#define RSC_HOT_EVENT_COND4_THM_USR1_ATTR				\
{									\
	{.fg=CYAN,.bg=MAGENTA,.bf=0,.un=1},				\
	{.fg=CYAN,.bg=MAGENTA,.bf=0,.un=0},				\
	{.fg=CYAN,.bg=MAGENTA,.bf=0,.un=0}				\
}

#define RSC_BOX_EVENT_THM_USR1_ATTR					\
{									\
	LKW,								\
	LMK,								\
	HYK								\
}

#define RSC_CREATE_RECORDER_THM_USR1_ATTR				\
{									\
	LKW,LKW,LKW,LKW,HKW,LKW,LKW,HKW,LKW,LKW,LKW,LKW 		\
}

#define RSC_SMBIOS_ITEM_THM_USR1_ATTR					\
{									\
	HKW,LCW,LCW,HKW,HKW,						\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW \
}

#define RSC_CREATE_SELECT_FREQ_PKG_THM_USR1_ATTR			\
{									\
	HYK,HYK,HYK,HYK,HYK,HYK,HYK,HYK,HYK,LKW,LKW,LKW,LKW,LKW,LKW,LKW,\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HYK,HYK,HYK,HYK,HYK,HYK,\
	HYK,HYK,HKW,HKW,HKW,LKW,LKW,HYK,HYK,HYK,HYK,HYK,LKW,LKW 	\
}

#define RSC_CREATE_SELECT_FREQ_COND0_THM_USR1_ATTR			\
{									\
	LCW,LCW,LCW,LCW,LCW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,		\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,		\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,HKW,HKW,HKW,			\
	LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW,LKW				\
}

#define RSC_CREATE_SELECT_FREQ_COND1_THM_USR1_ATTR			\
{									\
	LBK,LBK,LBK,LBK,LBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,		\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,		\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,			\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK				\
}
