/*
 * CoreFreq
 * Copyright (C) 2015-2022 CYRIL INGENIERIE
 * Licenses: GPL2
 */

#define RSC_THEME_USR2_CODE		/* 72 chars */			\
"        Transparent theme by leaty.  Updated by CyrIng - May 2022       "

#define RSC_UI_THM_USR2_ATTR						\
{									\
	[UI_FUSE_RESET_LAYER] = {					\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_FUSE_PAINT_LAYER] = {					\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_MAKE_TITLE_UNFOCUS] = {					\
		.fg = BLACK, .un = 0, .bg = BLUE, .bf = 1		\
	},								\
	[UI_MAKE_TITLE_FOCUS] = {					\
		.fg = WHITE, .un = 0, .bg = CYAN, .bf = 1		\
	},								\
	[UI_MAKE_BORDER_UNFOCUS] = {					\
		.fg = BLACK, .un = 0, .bg = BLUE, .bf = 1		\
	},								\
	[UI_MAKE_BORDER_FOCUS] = {					\
		.fg = WHITE, .un = 0, .bg = BLUE, .bf = 1		\
	},								\
	[UI_MAKE_SELECT_UNFOCUS] = {					\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_MAKE_SELECT_FOCUS] = {					\
		.fg = MAGENTA, .un = 1, .bg = BLACK, .bf = 0		\
	},								\
	[UI_MAKE_PRINT_UNFOCUS] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_MAKE_PRINT_FOCUS] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_MAKE_PRINT_DROP] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_LAYOUT_LCD_RESET] = {					\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_CLOCK_LOW] = {					\
		.fg = GREEN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_CLOCK_MEDIUM] = {				\
		.fg = YELLOW, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_CLOCK_HIGH] = {					\
		.fg = RED, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_COUNTER_LOW] =  {				\
		.fg = RED, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_COUNTER_MEDIUM] = {				\
		.fg = YELLOW, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_COUNTER_HIGH] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_LOAD_LOW] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_LOAD_MEDIUM] =  {				\
		.fg = YELLOW, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_LOAD_HIGH] = {					\
		.fg = RED, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_IDLE_LOW] = {					\
		.fg = YELLOW, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_IDLE_MEDIUM] =  {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_IDLE_HIGH] = {					\
		.fg = GREEN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_SYSTEM_LOW] = {					\
		.fg = RED, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_SYSTEM_MEDIUM] = {				\
		.fg = YELLOW, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_LCD_SYSTEM_HIGH] =  {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_UBENCH] = {						\
		.fg = MAGENTA, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_HEADER_PROC_BRAND] = {				\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_HEADER_PROC_BRAND_FILL] = {				\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_HEADER_ARCHITECTURE] = {				\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_HEADER_ARCH_FILL] = {				\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_HEADER_BCLK_FILL] = {				\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_RULER_INSTRUCTIONS] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_CYCLES] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_CSTATES] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_INTERRUPTS] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_PACKAGE] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_TASKS_FILL] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_TASKS_TRACKING] = {				\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_ENERGY] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_SLICE] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_CUSTOM] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_ENABLE_0] =  {				\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_ENABLE_1] =  {				\
		.fg = GREEN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_ENABLE_2] =  {				\
		.fg = BLUE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_TSC_NONE] =  {				\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_TSC_VAR] = {					\
		.fg = BLUE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_TSC_INV] = {					\
		.fg = GREEN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_TM_0] = {					\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_TM_1] = {					\
		.fg = BLUE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_TM_2] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_TM_3] = {					\
		.fg = GREEN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_FILL] = {					\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_GATE] = {					\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_SPACE] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_LEFT_BRACE] = {				\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_RIGHT_BRACE] = {				\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_KERNEL_VERSION] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_FOOTER_UNMAP_GATE] = {				\
		.fg = RED, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_FOOTER_DMI_STRING] = {				\
		.fg = BLUE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_BCLK_TO_VIEW] = {					\
		.fg = YELLOW, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_ROW_CPU_OFFLINE] =  {				\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_LOAD_TAB_DIM] = {				\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_LAYOUT_RULER_LOAD_TAB_BRIGHT] = {				\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_ILLUMINATES_CPU_OFF] = {					\
		.fg = BLUE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_ILLUMINATES_CPU_ON] = {					\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_ILLUMINATES_CPU_SP] = {					\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_ILLUMINATES_CPU_SP_HYBRID] = {				\
		.fg = GREEN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_DRAW_FREQUENCY_LOAD_CLEAR] = {				\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_DRAW_FREQUENCY_LOAD_LOW] = {				\
		.fg = GREEN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_DRAW_FREQUENCY_LOAD_MEDIUM] = {				\
		.fg = YELLOW, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_DRAW_FREQUENCY_LOAD_HIGH] = {				\
		.fg = RED, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_DRAW_ALTMONITOR_TASKS_CLEAR] = {				\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_DRAW_ALTMONITOR_TASKS_SPACE] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_DRAW_MONITOR_FREQUENCY_NOMINAL] =  {			\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_DRAW_MONITOR_FREQUENCY_LOW] = {				\
		.fg = BLUE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_DRAW_MONITOR_FREQUENCY_HIGH] = {				\
		.fg = YELLOW, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_DRAW_MONITOR_FREQUENCY_HOT] = {				\
		.fg = RED, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_CARD_CORE_OFFLINE] = {				\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_CARD_RAM_2DIGITS] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_LAYOUT_CARD_RAM_3DIGITS] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_DRAW_CARD_CORE_NOMINAL] =  {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_DRAW_CARD_CORE_LOW] = {					\
		.fg = BLUE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_DRAW_CARD_CORE_MEDIUM] = {					\
		.fg = YELLOW, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_DRAW_CARD_CORE_HIGH] = {					\
		.fg = RED, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_DRAW_CARD_TASK_FILL] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_MENU_UNSELECT] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_WIN_MENU_SELECT] = {					\
		.fg = MAGENTA, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_MENU_TITLE_UNFOCUS] =  {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_WIN_MENU_TITLE_FOCUS] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_WIN_MENU_ERASE_CELL] = {					\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_SORT_BY_FIELD_TITLE] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_WIN_TRACKING_PARENT_PROCESS] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_WIN_TRACKING_CHILD_PROCESS] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_WIN_TRACKING_COUNTERS] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_WIN_TRACKING_TITLE] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_WIN_HOT_PLUG_CPU_TITLE] =  {				\
		.fg = WHITE, .un = 0, .bg = BLUE, .bf = 1		\
	},								\
	[UI_WIN_SELECT_IDLE_RESET] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_SELECT_IDLE_POLL] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_SELECT_IDLE_CURRENT] = {				\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_POPUP_MSG_ITEM] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_POPUP_MSG_SELECT_UNFOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_POPUP_MSG_SELECT_FOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_POPUP_MSG_BORDER_UNFOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = RED, .bf = 0		\
	},								\
	[UI_WIN_POPUP_MSG_BORDER_FOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = RED, .bf = 1		\
	},								\
	[UI_WIN_POPUP_MSG_TITLE_UNFOCUS] = {				\
		.fg = WHITE, .un = 0, .bg = RED, .bf = 0		\
	},								\
	[UI_WIN_POPUP_MSG_TITLE_FOCUS] = {				\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 0		\
	},								\
	[UI_WIN_EXIT_ISSUE_RECORDER] = {				\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_ISSUE_STRESS] = {					\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_ISSUE_OS_CPU_IDLE] = {				\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_HEADER] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_WIN_EXIT_BLANK] =  {					\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_CONFIRM] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WIN_EXIT_FOOTER] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_BOX_DISABLE_STATE] = {					\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_BOX_ENABLE_STATE] = {					\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_BOX_BLANK] = {						\
		.fg = BLACK, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_BOX_DESC] = {						\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_BOX_INTERVAL] = {						\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	},								\
	[UI_BOX_EXPERIMENTAL_NOMINAL] = {				\
		.fg = CYAN, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_BOX_EXPERIMENTAL_WARNING] = {				\
		.fg = RED, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_DROP_IDLE_ROUTE] = {					\
		.fg = BLACK, .un = 0, .bg = WHITE, .bf = 1		\
	},								\
	[UI_BOX_TOOLS_STOP] =  {					\
		.fg = RED, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WHEEL_CURRENT] = {						\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WHEEL_SELECT] = {						\
		.fg = CYAN, .un = 1, .bg = BLACK, .bf = 1		\
	},								\
	[UI_WHEEL_LIST] = {						\
		.fg = WHITE, .un = 0, .bg = BLACK, .bf = 0		\
	}								\
}

#define RSC_VOID_THM_USR2_ATTR						\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_RUN_STATE_COLOR_THM_USR2_ATTR	\
{						\
	HRK,HRK,HRK,HRK,HRK,HRK,HRK,HRK,	\
	HRK,HRK,HRK,HRK,HRK,HRK,HRK,HRK,	\
	HRK,HRK,HRK,HRK,HRK,HRK,HRK,HRK,	\
	HRK,HRK,HRK,HRK,HRK,HRK,HRK,HRK,	\
	HRK,HRK,HRK,HRK,HRK,HRK,HRK,HRK 	\
}

#define RSC_UNINT_STATE_COLOR_THM_USR2_ATTR	\
{						\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,	\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,	\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,	\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,	\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK 	\
}

#define RSC_ZOMBIE_STATE_COLOR_THM_USR2_ATTR	\
{						\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW,	\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW,	\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW,	\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW,	\
	LRW,LRW,LRW,LRW,LRW,LRW,LRW,LRW 	\
}

#define RSC_SLEEP_STATE_COLOR_THM_USR2_ATTR	\
{						\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,	\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,	\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,	\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,	\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 	\
}

#define RSC_WAIT_STATE_COLOR_THM_USR2_ATTR	\
{						\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,	\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,	\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,	\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,	\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK 	\
}

#define RSC_OTHER_STATE_COLOR_THM_USR2_ATTR	\
{						\
	LGK,LGK,LGK,LGK,LGK,LGK,LGK,LGK,	\
	LGK,LGK,LGK,LGK,LGK,LGK,LGK,LGK,	\
	LGK,LGK,LGK,LGK,LGK,LGK,LGK,LGK,	\
	LGK,LGK,LGK,LGK,LGK,LGK,LGK,LGK,	\
	LGK,LGK,LGK,LGK,LGK,LGK,LGK,LGK 	\
}

#define RSC_TRACKER_STATE_COLOR_THM_USR2_ATTR	\
{						\
	LKC,LKC,LKC,LKC,LKC,LKC,LKC,LKC,	\
	LKC,LKC,LKC,LKC,LKC,LKC,LKC,LKC,	\
	LKC,LKC,LKC,LKC,LKC,LKC,LKC,LKC,	\
	LKC,LKC,LKC,LKC,LKC,LKC,LKC,LKC,	\
	LKC,LKC,LKC,LKC,LKC,LKC,LKC,LKC 	\
}

#define RSC_LAYOUT_HEADER_PROC_THM_USR2_ATTR				\
{									\
	HRK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK 		\
}

#define RSC_LAYOUT_HEADER_CPU_THM_USR2_ATTR				\
{									\
	HDK,HWK,HWK,HWK,HWK,HDK,HWK,HWK,HWK,HWK,LWK,LWK,LWK		\
}

#define RSC_LAYOUT_HEADER_ARCH_THM_USR2_ATTR				\
{									\
	HCK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK	\
}

#define RSC_LAYOUT_HEADER_CACHE_L1_THM_USR2_ATTR			\
{									\
	HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,				\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,HWK,HWK,HWK,			\
	LWK,LWK,LWK,LWK,HDK,HWK,HWK,HWK,LWK,LWK 			\
}

#define RSC_LAYOUT_HEADER_BCLK_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,		\
	HYK,HYK,HYK,HYK,HYK,HDK,HYK,HYK,HYK,HDK,HYK,HYK,HYK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_HEADER_CACHES_THM_USR2_ATTR				\
{									\
	LWK,LWK,HDK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,			\
	LWK,LWK,HDK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK			\
}

#define RSC_LAYOUT_RULER_LOAD_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,_HCK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_RULER_VAR_LOAD_THM_USR2_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK 							\
}

#define RSC_LAYOUT_RULER_REL_LOAD_THM_USR2_ATTR \
	RSC_LAYOUT_RULER_VAR_LOAD_THM_USR2_ATTR

#define RSC_LAYOUT_RULER_ABS_LOAD_THM_USR2_ATTR \
	RSC_LAYOUT_RULER_VAR_LOAD_THM_USR2_ATTR

#define RSC_LAYOUT_MONITOR_FREQUENCY_THM_USR2_ATTR			\
{									\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HDK,HDK,HWK,HWK,HWK,HWK,HWK,HDK,\
	HDK,HWK,HWK,HWK,HWK,HWK,HWK,HDK,HDK,HWK,HWK,HWK,HWK,HWK,HWK,HDK,\
	HDK,HWK,HWK,HWK,HWK,HWK,HWK,HDK,HDK,HWK,HWK,HWK,HWK,HWK,HWK,HDK,\
	HDK,HWK,HWK,HWK,HWK,HWK,HWK,HDK,HDK,HWK,HWK,HWK,HWK,HWK,HWK,HDK,\
	HDK,HDK,HBK,HBK,HBK,HDK,LWK,LWK,LWK,HDK,LYK,LYK,LYK		\
}

#define RSC_LAYOUT_MONITOR_INST_THM_USR2_ATTR				\
{									\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HDK,LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HDK,LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HDK,LWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK		\
}

#define RSC_LAYOUT_MONITOR_COMMON_THM_USR2_ATTR 			\
{									\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK		\
}

#define RSC_LAYOUT_MONITOR_TASKS_THM_USR2_ATTR				\
{									\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_MONITOR_SLICE_THM_USR2_ATTR				\
{									\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HRK,HRK,HRK,\
	HRK,HRK,HRK,HRK,HRK,HRK,HRK,HRK,HRK,HRK,HRK,HRK,HRK,HRK,HRK	\
}

#define RSC_LAYOUT_CUSTOM_FIELD_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,				\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,				\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,				\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,				\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,				\
	LWK,LWK,LWK,LWK,						\
	HWK,HWK,HWK,LWK,						\
	LWK,LWK,LWK,LWK,						\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,				\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,				\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,				\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,				\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,				\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,				\
	HWK,HWK,HWK,HWK,HWK,HWK,LWK,					\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,					\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,					\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,					\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,					\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,			\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,			\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 	\
}

#define RSC_LAYOUT_RULER_FREQUENCY_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_RULER_FREQUENCY_AVG_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,_HCK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_RULER_FREQUENCY_PKG_THM_USR2_ATTR			\
{									\
	_HCK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,HDK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_RULER_INST_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_RULER_CYCLES_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_RULER_CSTATES_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_RULER_INTERRUPTS_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_RULER_PACKAGE_THM_USR2_ATTR	RSC_VOID_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,HDK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HDK,HDK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK \
}

#define RSC_LAYOUT_PACKAGE_PC02_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_PC03_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_PC04_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_PC06_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_PC07_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_PC08_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_PC09_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_PC10_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_MC06_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_CTR0_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_CTR1_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_CTR2_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_CTR3_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_CTR4_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_CTR5_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_CTR6_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_CTR7_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_FCLK_THM_USR2_ATTR	\
	RSC_LAYOUT_PACKAGE_PC_THM_USR2_ATTR

#define RSC_LAYOUT_PACKAGE_UNCORE_THM_USR2_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,HDK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_PACKAGE_FABRIC_THM_USR2_ATTR \
	RSC_LAYOUT_PACKAGE_UNCORE_THM_USR2_ATTR

#define RSC_LAYOUT_RULER_TASKS_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LDK,LDK,LDK,LDK,LDK,LDK,LDK,LDK,LDK,\
	LDK,LDK,LDK,LDK,LDK,LDK,LDK,LDK,LDK,LDK,LDK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_TASKS_STATE_SORTED_THM_USR2_ATTR			\
{									\
	HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,_HCK,LWK,			\
	LWK,LCK,LCK,LCK,LCK,LCK,HDK,LWK, LWK,LWK,LWK			\
}

#define RSC_LAYOUT_TASKS_RUNTIME_SORTED_THM_USR2_ATTR			\
{									\
	HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,_HCK,LWK,			\
	LWK,LCK,LCK,LCK,LCK,LCK,LCK,LCK, HDK,LWK,LWK			\
}

#define RSC_LAYOUT_TASKS_USRTIME_SORTED_THM_USR2_ATTR			\
{									\
	HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,_HCK,LWK,			\
	LWK,LCK,LCK,LCK,LCK,LCK,LCK,LCK, LCK,HDK,LWK			\
}

#define RSC_LAYOUT_TASKS_SYSTIME_SORTED_THM_USR2_ATTR			\
{									\
	HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,_HCK,LWK,			\
	LWK,LCK,LCK,LCK,LCK,LCK,LCK,LCK, HDK,LWK,LWK			\
}

#define RSC_LAYOUT_TASKS_PROCESS_SORTED_THM_USR2_ATTR			\
{									\
	HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,_HCK,LWK,			\
	LWK,LCK,LCK,LCK,HDK,LWK,LWK,LWK, LWK,LWK,LWK			\
}

#define RSC_LAYOUT_TASKS_COMMAND_SORTED_THM_USR2_ATTR			\
{									\
	HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,_HCK,LWK,			\
	LWK,LCK,LCK,LCK,LCK,LCK,LCK,LCK, HDK,LWK,LWK			\
}

#define RSC_LAYOUT_TASKS_REVERSE_SORT_OFF_THM_USR2_ATTR 		\
{									\
	LWK,LWK,LWK,LWK,LWK,_HCK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,HDK,LWK	\
}

#define RSC_LAYOUT_TASKS_REVERSE_SORT_ON_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,_HCK,LWK,LWK,LWK,HDK,LCK,LCK,LCK,HDK,LWK	\
}

#define RSC_LAYOUT_TASKS_VALUE_SWITCH_THM_USR2_ATTR			\
{									\
	LWK,_HCK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,HDK,LWK		\
}

#define RSC_LAYOUT_TASKS_VALUE_OFF_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK							\
}

#define RSC_LAYOUT_TASKS_VALUE_ON_THM_USR2_ATTR 			\
{									\
	LCK,LCK,LCK							\
}

#define RSC_LAYOUT_TASKS_TRACKING_THM_USR2_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,_HCK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK					\
}

#define RSC_LAYOUT_RULER_SENSORS_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,\
	LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,HDK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,HDK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_RULER_PWR_DOMAIN_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,HDK,HWK,HWK,HWK,LWK,HWK,HWK,HWK,HWK,HDK,LWK,HDK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,HWK,HWK,HWK,LWK,HWK,HWK,\
	HWK,HWK,HDK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,\
	HWK,HWK,HWK,LWK,HWK,HWK,HWK,HWK,HDK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,HDK,HWK,HWK,HWK,LWK,HWK,HWK,HWK,HWK,HDK,LWK,HDK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_RULER_PWR_UNCORE_THM_USR2_ATTR	\
	RSC_LAYOUT_RULER_PWR_DOMAIN_THM_USR2_ATTR

#define RSC_LAYOUT_RULER_PWR_PLATFORM_THM_USR2_ATTR	\
	RSC_LAYOUT_RULER_PWR_DOMAIN_THM_USR2_ATTR

#define RSC_LAYOUT_RULER_PWR_SOC_THM_USR2_ATTR		\
	RSC_LAYOUT_RULER_PWR_DOMAIN_THM_USR2_ATTR

#define RSC_LAYOUT_RULER_VOLTAGE_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,HDK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,HDK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_RULER_VPKG_SOC_THM_USR2_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,\
	HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HDK,LWK,HDK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,HDK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_RULER_VPKG_SAV_THM_USR2_ATTR 			\
	RSC_LAYOUT_RULER_VPKG_SOC_THM_USR2_ATTR

#define RSC_LAYOUT_RULER_ENERGY_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_RULER_POWER_THM_USR2_ATTR	\
	RSC_LAYOUT_RULER_ENERGY_THM_USR2_ATTR

#define RSC_LAYOUT_RULER_SLICE_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_RULER_CUSTOM_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_LAYOUT_FOOTER_TECH_X86_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,LWK 	\
}

#define RSC_LAYOUT_FOOTER_TECH_INTEL_THM_USR2_ATTR			\
{									\
	HDK,HDK,HDK,LWK,HDK,HDK,HDK,HDK,LWK,HDK,HDK,HDK,LWK,		\
	HDK,HDK,HDK,HDK,HDK,LWK,HDK,HDK,HDK,LWK,			\
	HDK,HDK,HDK,LWK,HDK,HDK,HDK,LWK,HDK,HDK,HDK,LWK,		\
	HDK,HDK,LWK,HDK,HDK,HDK,HDK,LWK,				\
	HDK,HDK,LWK,HDK,HDK,HDK,HDK,HDK 				\
}

#define RSC_LAYOUT_FOOTER_TECH_AMD_THM_USR2_ATTR			\
{									\
	HDK,HDK,HDK,LWK,HDK,HDK,HDK,LWK,HDK,HDK,HDK,HDK,LWK,		\
	HDK,HDK,HDK,HDK,HDK,LWK,HDK,HDK,HDK,LWK,HDK,HDK,HDK,		\
	LWK,HDK,HDK,HDK,LWK,HDK,HDK,HDK,LWK,HDK,HDK,HDK,LWK,		\
	HDK,HDK,LWK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK		\
}

#define RSC_LAYOUT_FOOTER_VOLT_TEMP_THM_USR2_ATTR			\
{									\
	LWK,HDK,HWK,HWK,HWK,HWK,HDK,HDK,LWK,HDK,HDK,HDK,HDK,LWK,HDK	\
}

#define RSC_LAYOUT_FOOTER_SYSTEM_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,HDK,HWK,HWK,HWK,HWK,HWK,HWK,HDK,	\
	LWK,LWK,LWK,LWK,LWK,HDK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,	\
	HWK,HDK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,HDK 	\
}

#define RSC_LAYOUT_CARD_CORE_ONLINE_THM_USR2_ATTR			\
{									\
	HDK,HDK,LCK,LCK,LCK,HDK,HDK,HDK,HDK,HDK,HDK,HDK 		\
}

#define RSC_LAYOUT_CARD_CORE_ONLINE_COND0_THM_USR2_ATTR \
	RSC_LAYOUT_CARD_CORE_ONLINE_THM_USR2_ATTR

#define RSC_LAYOUT_CARD_CORE_ONLINE_COND1_THM_USR2_ATTR \
	RSC_LAYOUT_CARD_CORE_ONLINE_THM_USR2_ATTR

#define RSC_LAYOUT_CARD_CORE_OFFLINE_THM_USR2_ATTR			\
{									\
	HDK,HDK,LBK,LBK,LBK,HDK,HDK,LWK,LWK,LWK,HDK,HDK 		\
}

#define RSC_LAYOUT_CARD_CLK_THM_USR2_ATTR				\
{									\
	HDK,HDK,HWK,HWK,HWK,LWK,HWK,HDK,HDK,HDK,HDK,HDK 		\
}

#define RSC_LAYOUT_CARD_UNCORE_THM_USR2_ATTR				\
{									\
	HDK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,HDK,LCK,LCK,HDK 		\
}

#define RSC_LAYOUT_CARD_BUS_THM_USR2_ATTR				\
{									\
	HDK,LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,HDK,HDK,HDK 		\
}

#define RSC_LAYOUT_CARD_MC_THM_USR2_ATTR				\
{									\
	HDK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK 		\
}

#define RSC_LAYOUT_CARD_LOAD_THM_USR2_ATTR				\
{									\
	HDK,HDK,HDK,HDK,LWK,LWK,LWK,LWK,LWK,HDK,HDK,HDK 		\
}

#define RSC_LAYOUT_CARD_IDLE_THM_USR2_ATTR				\
{									\
	HDK,HDK,HDK,HDK,LWK,LWK,LWK,LWK,LWK,HDK,HDK,HDK 		\
}

#define RSC_LAYOUT_CARD_RAM_THM_USR2_ATTR				\
{									\
	HDK,HWK,HWK,HWK,HWK,HWK,LWK,HDK,HWK,HWK,LDK,HDK 		\
}

#define RSC_LAYOUT_CARD_TASK_THM_USR2_ATTR				\
{									\
	HDK,LWK,LWK,LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,HDK 		\
}

#define RSC_SYSINFO_CPUID_COND0_THM_USR2_ATTR				\
{									\
	HWK,HWK,HWK,LWK,HDK,LCK,LCK,LCK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_CPUID_COND1_THM_USR2_ATTR				\
{									\
	HBK,HBK,HBK,HBK,HBK,LBK,LBK,LBK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_CPUID_COND2_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,HWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_CPUID_COND3_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,\
	LWK,LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,\
	LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,HWK,HWK,\
	HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_SYSTEM_REGISTERS_COND0_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK 						\
}

#define RSC_SYSTEM_REGISTERS_COND1_THM_USR2_ATTR			\
{									\
	HBK,HBK,HBK,HBK 						\
}

#define RSC_SYSTEM_REGISTERS_COND2_THM_USR2_ATTR			\
{									\
	HWK,HWK,HWK,HWK 						\
}

#define RSC_SYSTEM_REGISTERS_COND3_THM_USR2_ATTR			\
{									\
	HDK,LCK,LCK,LCK 						\
}

#define RSC_SYSTEM_REGISTERS_COND4_THM_USR2_ATTR			\
{									\
	HDK,LBK,LBK,LBK 						\
}

#define RSC_SYSINFO_PROC_COND0_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 		\
}

#define RSC_SYSINFO_PROC_COND1_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,HGK,HGK,HGK,HGK,HGK,HGK,HGK,LWK,LWK 		\
}

#define RSC_SYSINFO_PROC_COND2_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK 		\
}

#define RSC_SYSINFO_PROC_COND3_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK 		\
}

#define RSC_SYSINFO_ISA_COND_0_0_THM_USR2_ATTR				\
{	/*	[N] & [N/N]	2*(0|0)+(0<<0)			*/	\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_0_1_THM_USR2_ATTR				\
{	/*	[Y]						*/	\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,HGK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_0_2_THM_USR2_ATTR				\
{	/*	[N/Y]	2*(0|1)+(0<<1)				*/	\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,HGK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_0_3_THM_USR2_ATTR				\
{	/*	[Y/N]	2*(1|0)+(1<<0)				*/	\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,HGK,LWK,LWK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_0_4_THM_USR2_ATTR				\
{	/*	[Y/Y]	2*(1|1)+(1<<1)				*/	\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,HGK,LWK,HGK,LWK					\
}

#define RSC_SYSINFO_ISA_COND_1_0_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_1_1_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,HGK,LWK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_1_2_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,HGK,LWK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_1_3_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,HGK,LWK,LWK,LWK,LWK					\
}
#define RSC_SYSINFO_ISA_COND_1_4_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,HGK,LWK,HGK,LWK,LWK					\
}

#define RSC_SYSINFO_FEATURES_COND0_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK 							\
}

#define RSC_SYSINFO_FEATURES_COND1_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,			\
	LWK,LWK 							\
}

#define RSC_SYSINFO_FEATURES_COND2_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LCK,LCK,LCK,LCK,LCK,LCK,LCK,			\
	LWK,LWK 							\
}

#define RSC_SYSINFO_FEATURES_COND3_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,HGK,HGK,HGK,HGK,HGK,HGK,HGK,			\
	LWK,LWK 							\
}

#define RSC_SYSINFO_FEATURES_COND4_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,HGK,HGK,HGK,HGK,HGK,HGK,HGK,HGK,HGK,			\
	LWK,LWK 							\
}

#define RSC_SYSINFO_TECH_COND0_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_TECH_COND1_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,HGK,HGK,HGK,LWK,LWK 			\
}

#define RSC_SYSINFO_PERFMON_COND0_THM_USR2_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK 						\
}

#define RSC_SYSINFO_PERFMON_COND1_THM_USR2_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HGK,			\
	HGK,HGK,LWK,LWK 						\
}

#define RSC_SYSINFO_PERFMON_COND2_THM_USR2_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,HBK,HBK,HBK,HBK,HBK,			\
	HBK,HBK,LWK,LWK 						\
}

#define RSC_SYSINFO_PERFMON_COND3_THM_USR2_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,HGK,HGK,HGK,HGK,HGK,			\
	HGK,HGK,LWK,LWK 						\
}

#define RSC_SYSINFO_PERFMON_COND4_THM_USR2_ATTR 			\
{									\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK 						\
}

#define RSC_SYSINFO_PERFMON_HWP_CAP_COND0_THM_USR2_ATTR 		\
{									\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK 	 		\
}

#define RSC_SYSINFO_PERFMON_HWP_CAP_COND1_THM_USR2_ATTR 		\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 	 		\
}

#define RSC_SYSINFO_PWR_THERMAL_COND0_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND1_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,LWK,LWK 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND2_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LGK,LGK,LGK,LGK,LGK,LGK,LGK,LWK,LWK 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND3_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,HGK,HGK,HGK,HGK,HGK,HGK,HGK,LWK,LWK 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND4_THM_USR2_ATTR			\
{									\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,			\
	HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK,HDK 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND5_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_PWR_THERMAL_COND6_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HWK,			\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK 			\
}

#define RSC_SYSINFO_KERNEL_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 				\
}

#define RSC_TOPOLOGY_COND0_THM_USR2_ATTR				\
{									\
	HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK		\
}

#define RSC_TOPOLOGY_COND1_THM_USR2_ATTR				\
{									\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK		\
}

#define RSC_TOPOLOGY_COND2_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK		\
}

#define RSC_TOPOLOGY_COND3_THM_USR2_ATTR				\
{									\
	LCK,LCK,LCK,HDK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK,HWK		\
}

#define RSC_TOPOLOGY_COND4_THM_USR2_ATTR				\
{									\
	LBK,LBK,LBK,HDK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK		\
}

#define RSC_MEMORY_CONTROLLER_COND0_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK						\
}

#define RSC_MEMORY_CONTROLLER_COND1_THM_USR2_ATTR			\
{									\
	HWK,HWK,HWK,HWK,HWK						\
}

#define RSC_CREATE_MENU_DISABLE_THM_USR2_ATTR				\
{									\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,		\
	HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW,HKW 		\
}

#define RSC_MENU_ITEM_MENU_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,HKW,_LWK,_LWK,HKW,LWK,LWK,LWK,		\
	LWK,LWK,LWK,LWK,LWK,LWK, LWK, LWK,LWK,LWK,LWK,LWK		\
}

#define RSC_MENU_ITEM_VIEW_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,HKW,_LWK,_LWK,HKW,LWK,LWK,LWK,		\
	LWK,LWK,LWK,LWK,LWK,LWK, LWK, LWK,LWK,LWK,LWK,LWK		\
}

#define RSC_MENU_ITEM_WINDOW_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,HKW,_LWK,_LWK,HKW,LWK,LWK,LWK,LWK,		\
	LWK,LWK,LWK,LWK,LWK, LWK, LWK,LWK,LWK,LWK,LWK,LWK		\
}

#define RSC_CREATE_MENU_FN_KEY_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK, LWK,LWK,LWK,LWK,		\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,HKW,_LWK,_LWK,HKW,LWK		\
}

#define RSC_CREATE_MENU_SHORTKEY_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK, LWK,LWK,LWK,		\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HKW,_LWK,HKW,LWK		\
}

#define RSC_CREATE_MENU_CTRL_KEY_THM_USR2_ATTR				\
{									\
	LWK,LWK, LWK, LWK, LWK, LWK,LWK,LWK,LWK, LWK,LWK,LWK,		\
	LWK,HKW,_LWK,_LWK,_LWK,_LWK,HKW,HKW,HKW,_LWK,HKW,LWK		\
}

#define RSC_CREATE_SETTINGS_COND0_THM_USR2_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,LWK,LWK,LWK,HDK,LWK \
}

#define RSC_CREATE_SETTINGS_COND1_THM_USR2_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,HGK,HGK,HGK,HDK,LWK \
}

#define RSC_CREATE_ADV_HELP_COND0_THM_USR2_ATTR 			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 				\
}

#define RSC_CREATE_ADV_HELP_COND1_THM_USR2_ATTR 			\
{									\
	LWK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,			\
	HCK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK 				\
}

#define RSC_CREATE_HOTPLUG_CPU_ENABLE_THM_USR2_ATTR			\
{									\
	LWK,LGK,LGK,LGK,LGK,LGK,LGK,LGK,LGK,LGK,LGK,LWK,LDK,LDK,LDK	\
}

#define RSC_CREATE_HOTPLUG_CPU_DISABLE_THM_USR2_ATTR			\
{									\
	LWK,LCK,LCK,LCK,LCK,LCK,LCK,LCK,LCK,LCK,LCK,LWK,LDK,LDK,LDK	\
}

#define RSC_CREATE_HOTPLUG_CPU_ONLINE_THM_USR2_ATTR			\
{									\
	LCK,LCK,LCK,LCK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_HOTPLUG_CPU_OFFLINE_THM_USR2_ATTR			\
{									\
	LBK,LBK,LBK,LBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND0_THM_USR2_ATTR			\
{									\
	LWK,HWK,HWK,HWK,HWK,LWK,HWK,HWK,LWK,HDK,HDK,HDK,LWK,LWK,	\
	LWK,LWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND1_THM_USR2_ATTR			\
{									\
	LWK,HBK,HBK,HBK,HBK,LBK,HBK,HBK,LWK,HDK,HDK,HDK,LWK,LWK,	\
	LWK,LWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND2_THM_USR2_ATTR			\
{									\
	LWK,HRK,HRK,HRK,HRK,LRK,HRK,HRK,LWK,HDK,HDK,HDK,LWK,LWK,	\
	LWK,LWK,HWK,HWK,HWK,HWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND3_THM_USR2_ATTR			\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,	\
	LWK,LWK,HCK,HCK,HCK,HCK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND4_THM_USR2_ATTR			\
{									\
	LWK,HWK,HWK,HWK,HWK,LWK,HWK,HWK,LWK,HDK,HDK,HDK,LWK,LWK,	\
	LWK,LWK,HCK,HCK,HCK,HCK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND5_THM_USR2_ATTR			\
{									\
	LWK,HBK,HBK,HBK,HBK,LBK,HBK,HBK,LWK,HDK,HDK,HDK,LWK,LWK,	\
	LWK,LWK,HCK,HCK,HCK,HCK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_RATIO_CLOCK_COND6_THM_USR2_ATTR			\
{									\
	LWK,HRK,HRK,HRK,HRK,LRK,HRK,HRK,LWK,HDK,HDK,HDK,LWK,LWK,	\
	LWK,LWK,HCK,HCK,HCK,HCK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK	\
}

#define RSC_CREATE_SELECT_CPU_COND0_THM_USR2_ATTR			\
{									\
	LBK,LBK,LBK,LBK,LBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,		\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,		\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK 			\
}

#define RSC_CREATE_SELECT_CPU_COND1_THM_USR2_ATTR			\
{									\
	LCK,LCK,LCK,LCK,LCK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,		\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,		\
	LWK,LWK,LCK,LCK,LCK,LWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_CREATE_SELECT_CPU_COND2_THM_USR2_ATTR			\
{									\
	LCK,LCK,LCK,LCK,LCK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,		\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,		\
	LWK,LWK,HRK,HRK,HRK,LWK,LWK,LWK,LWK,LWK 			\
}

#define RSC_HOT_EVENT_COND0_THM_USR2_ATTR				\
{									\
	HDK,HDK,HDK							\
}

#define RSC_HOT_EVENT_COND1_THM_USR2_ATTR				\
{									\
	HRK,HRK,HRK							\
}

#define RSC_HOT_EVENT_COND2_THM_USR2_ATTR				\
{									\
	{.fg=CYAN,.bg=BLACK,.bf=1,.un=1},				\
	{.fg=CYAN,.bg=BLACK,.bf=0,.un=0},				\
	{.fg=CYAN,.bg=BLACK,.bf=0,.un=0}				\
}

#define RSC_HOT_EVENT_COND3_THM_USR2_ATTR				\
{									\
	HWK,HWK,HWK							\
}

#define RSC_HOT_EVENT_COND4_THM_USR2_ATTR				\
{									\
	{.fg=CYAN,.bg=MAGENTA,.bf=0,.un=1},				\
	{.fg=CYAN,.bg=MAGENTA,.bf=0,.un=0},				\
	{.fg=CYAN,.bg=MAGENTA,.bf=0,.un=0}				\
}

#define RSC_BOX_EVENT_COND00_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK \
}

#define RSC_BOX_EVENT_COND01_THM_USR2_ATTR				\
{									\
	LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,HDK \
}

#define RSC_BOX_EVENT_COND10_THM_USR2_ATTR				\
{									\
	LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,LKY,HDK \
}

#define RSC_BOX_EVENT_COND11_THM_USR2_ATTR				\
{									\
	LKY,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LWM,LKY,HDK \
}

#define RSC_BOX_EVENT_BUTTON_THM_USR2_ATTR				\
{									\
	LWK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,HCK,LWK \
}

#define RSC_CREATE_RECORDER_THM_USR2_ATTR				\
{									\
	LWK,LWK,LWK,LWK,HDK,LWK,LWK,HDK,LWK,LWK,LWK,LWK 		\
}

#define RSC_SMBIOS_ITEM_THM_USR2_ATTR					\
{									\
	HDK,LCK,LCK,HDK,HDK,						\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK \
}

#define RSC_CREATE_SELECT_FREQ_PKG_THM_USR2_ATTR			\
{									\
	HYK,HYK,HYK,HYK,HYK,HYK,HYK,HYK,HYK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HYK,HYK,HYK,HYK,HYK,HYK,\
	HYK,HYK,HDK,HDK,HDK,LWK,LWK,HYK,HYK,HYK,HYK,HYK,LWK,LWK 	\
}

#define RSC_CREATE_SELECT_FREQ_COND0_THM_USR2_ATTR			\
{									\
	LCK,LCK,LCK,LCK,LCK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,		\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,		\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,HDK,HDK,HDK,			\
	LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK,LWK				\
}

#define RSC_CREATE_SELECT_FREQ_COND1_THM_USR2_ATTR			\
{									\
	LBK,LBK,LBK,LBK,LBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,		\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,		\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,			\
	HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK,HBK				\
}

_Static_assert( __builtin_strlen(RSC_THEME_USR2_CODE)
	==	__builtin_strlen(RSC_BOX_THEME_BLANK_CODE),
"Mandatory string length");
