#!/bin/sh
#
# CoreFreq
# Copyright (C) 2015-2018 CYRIL INGENIERIE
# Licenses: GPL2
#

set -e

case "$1" in
remove|upgrade|deconfigure)
	PACKAGE="corefreq"
	MODULE="corefreqk"
	A_B_C_D=$(dpkg-query --show --showformat='${Version}' $PACKAGE 2>/dev/null)
	if [ -n "$A_B_C_D" ]; then
		A_B_C=${A_B_C_D%.*}
		VERSION=${A_B_C%.*}

		if [ "$(dkms status -m $MODULE)" ]; then
			modprobe -r $MODULE 2>/dev/null
			if [ $? -eq 0 ]; then
				echo "Module [${MODULE}] unloaded.\n"
			fi
			dkms remove $MODULE/$VERSION --all
		fi
	else
		echo "Pre Removal: Can not query [${PACKAGE}]\n" >&2
	fi
;;

failed-upgrade)
;;

*)
	echo "prerm: unknown argument \`$1'" >&2
	exit 1
;;
esac

#DEBHELPER#

exit 0
