#!/bin/sh
#
# CoreFreq
# Copyright (C) 2015-2018 CYRIL INGENIERIE
# Licenses: GPL2
#

set -e

case "$1" in
configure)
	PACKAGE="corefreq"
	MODULE="corefreqk"
	A_B_C_D=$(dpkg-query --show --showformat='${Version}' $PACKAGE 2>/dev/null)
	if [ -n "$A_B_C_D" ]; then
		A_B_C=${A_B_C_D%.*}
		VERSION=${A_B_C%.*}

		dkms install $MODULE/$VERSION
	else
		echo "Post Installation: Can not query [${PACKAGE}]\n" >&2
	fi
;;

abort-upgrade|abort-remove|abort-deconfigure)
;;

*)
	echo "postinst: unknown argument \`$1'" >&2
	exit 1
;;
esac

#DEBHELPER#

exit 0
